# -*- coding: utf-8 -*-
"""arkanoid19.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FVVKi1CmvawK-stjiRIrcJOwy1lnCita
"""

from IPython.display import display, HTML

html = """
<style>
#bs-wrap { background:#0a0a18; display:flex; flex-direction:column; align-items:center; padding:8px 0; border-radius:8px; }
#bs-wrap canvas { display:block; border:1px solid #00dcff33; cursor:default; }
#bs-info { color:#556; font-size:11px; margin-top:5px; font-family:monospace; }
</style>
<div id="bs-wrap">
<canvas id="bsc" width="700" height="560"></canvas>
<div id="bs-info">click en el juego primero · flechas/AD mover · espacio lanzar · P pausa · R reiniciar · ESC menu</div>
</div>
<script>
(function(){
const cv=document.getElementById('bsc');
const cx=cv.getContext('2d');
const W=700,H=560,HUD=44;
cv.setAttribute('tabindex','0');
cv.addEventListener('click',()=>cv.focus());

const BCOLS=10,BW=56,BH=20,BXG=4,BYG=4;
const BX0=Math.floor((W-BCOLS*(BW+BXG)+BXG)/2);
const BY0=HUD+24;
const BALL_R=6, PAD_BASE=90, PAD_H=11, PAD_SPD=6, PAD_Y=H-40;

const BCOLORS={1:'#50a0ff',2:'#ffa028',3:'#ff3250',steel:'#8c96aa'};
const PUCOLORS={expand:'#32dc50',slow:'#00dcff',life:'#ff64b4',shrink:'#ff3232'};
const PULABELS={expand:'+W',slow:'SL',life:'+1',shrink:'-W'};

const LVS=[
  [[1,1,1,1,1,1,1,1,1,1],[1,1,1,1,1,1,1,1,1,1],[1,1,1,1,1,1,1,1,1,1],
   [0,1,1,1,1,1,1,1,1,0],[0,0,1,1,1,1,1,1,0,0],[0,0,0,1,1,1,1,0,0,0],[0,0,0,0,0,0,0,0,0,0]],
  [[2,2,2,2,2,2,2,2,2,2],[2,1,1,1,1,1,1,1,1,2],[2,1,9,1,1,1,1,9,1,2],
   [2,1,1,0,0,0,0,1,1,2],[2,1,9,1,1,1,1,9,1,2],[2,1,1,1,1,1,1,1,1,2],[2,2,2,2,2,2,2,2,2,2]],
  [[3,3,3,3,3,3,3,3,3,3],[3,2,2,2,2,2,2,2,2,3],[3,2,1,1,9,9,1,1,2,3],
   [3,2,1,0,0,0,0,1,2,3],[3,2,1,1,9,9,1,1,2,3],[3,2,2,2,2,2,2,2,2,3],[3,3,3,3,3,3,3,3,3,3]]
];

const stars=[];
for(let i=0;i<160;i++) stars.push({x:Math.random()*W,y:Math.random()*H,s:Math.random()<0.6?1:2,spd:Math.random()*0.3+0.05,b:Math.floor(Math.random()*140+80)});

let ST='menu',score=0,lives=3,lv=1,combo=0,maxCombo=0;
let bricks=[],pups=[],pad,ball,msgT=0,tt=0,at=0;
const keys={};

cv.addEventListener('keydown',e=>{
  keys[e.code]=true;
  if(ST==='launching'&&(e.code==='Space'||e.code==='Enter')){ST='playing';}
  else if(e.code==='KeyP'){
    if(ST==='playing'||ST==='launching') ST='paused';
    else if(ST==='paused') ST='playing';
  }
  else if(e.code==='KeyR'){
    if(['playing','launching','paused','gameover','victory'].includes(ST)) loadLv();
  }
  else if(e.code==='Escape'){
    if(['playing','launching','paused','gameover','victory','instructions','credits'].includes(ST)) ST='menu';
  }
  e.preventDefault();
});
cv.addEventListener('keyup',e=>{keys[e.code]=false;});
cv.addEventListener('click',e=>{
  const r=cv.getBoundingClientRect();
  const mx=(e.clientX-r.left)*(W/r.width);
  const my=(e.clientY-r.top)*(H/r.height);
  onClick(mx,my);
});

function onClick(mx,my){
  if(ST==='menu'){
    const btns=[{a:'play'},{a:'instructions'},{a:'credits'},{a:'quit'}];
    btns.forEach(({a},i)=>{
      const bx=W/2-110,by=H/2+10+i*58,bw=220,bh=44;
      if(mx>=bx&&mx<=bx+bw&&my>=by&&my<=by+bh){
        if(a==='play') newGame();
        else if(a==='quit'){ST='menu';}
        else ST=a;
      }
    });
  } else if(ST==='launching'){ ST='playing'; }
  else if(ST==='gameover'||ST==='victory'){
    const cy2=H/2+100;
    if(mx>=W/2-230&&mx<=W/2-20&&my>=cy2&&my<=cy2+44) newGame();
    if(mx>=W/2+20&&mx<=W/2+230&&my>=cy2&&my<=cy2+44) ST='menu';
  }
}

function rr(x,y,w,h,r,fill,stroke,sw){
  cx.beginPath(); cx.roundRect(x,y,w,h,r);
  if(fill){cx.fillStyle=fill;cx.fill();}
  if(stroke){cx.strokeStyle=stroke;cx.lineWidth=sw;cx.stroke();}
}
function overlap(ax,ay,aw,ah,bx,by,bw,bh){return ax<bx+bw&&ax+aw>bx&&ay<by+bh&&ay+ah>by;}
function ct(text,font,color,y){cx.font=font;cx.fillStyle=color;cx.textAlign='center';cx.textBaseline='top';cx.fillText(text,W/2,y);}
function lerpC(a,b,t){return a.map((v,i)=>Math.round(v+(b[i]-v)*t));}

function newGame(){score=0;lives=3;lv=1;combo=0;maxCombo=0;loadLv();}
function loadLv(){
  pups=[];
  pad={x:(W-PAD_BASE)/2,y:PAD_Y,w:PAD_BASE,pw:null,pt:0};
  bricks=[];
  const grid=LVS[Math.min(lv-1,2)];
  grid.forEach((row,ri)=>row.forEach((v,ci)=>{
    if(!v) return;
    const type=v===9?'steel':'normal';
    bricks.push({x:BX0+ci*(BW+BXG),y:BY0+ri*(BH+BYG),hp:v===9?99:v,maxHp:v===9?99:v,type,alive:true,ft:0});
  }));
  const spd=4.5+(lv-1)*0.5;
  const ang=(Math.random()*80-40)*Math.PI/180;
  ball={x:pad.x+pad.w/2,y:pad.y-BALL_R-1,vx:spd*Math.sin(ang),vy:-spd*Math.cos(ang),trail:[],slowed:false,st:0};
  combo=0; ST='launching';
}

function updPad(dt){
  if(keys['ArrowLeft']||keys['KeyA']) pad.x-=PAD_SPD;
  if(keys['ArrowRight']||keys['KeyD']) pad.x+=PAD_SPD;
  pad.x=Math.max(0,Math.min(W-pad.w,pad.x));
  if(pad.pw){pad.pt-=dt;if(pad.pt<=0){pad.w=PAD_BASE;pad.pw=null;pad.x=Math.max(0,Math.min(W-pad.w,pad.x));}}
}
function applyPadPU(type){
  if(type==='expand'){pad.w=Math.round(PAD_BASE*1.55);pad.pw='expand';pad.pt=8;}
  if(type==='shrink'){pad.w=Math.round(PAD_BASE*0.60);pad.pw='shrink';pad.pt=6;}
  pad.x=Math.max(0,Math.min(W-pad.w,pad.x));
}
function drawPad(){
  const col=pad.pw==='expand'?'#00f078':pad.pw==='shrink'?'#ff8c00':'#00dcff';
  const brd=pad.pw==='expand'?'#00a050':pad.pw==='shrink'?'#c85a00':'#00a0d2';
  rr(pad.x,pad.y,pad.w,PAD_H,6,col,brd,2);
  cx.fillStyle='rgba(255,255,255,0.3)';rr(pad.x+4,pad.y+3,pad.w-8,3,2,'rgba(255,255,255,0.3)',null,0);
  if(pad.pw){const mt=pad.pw==='expand'?8:6;const ratio=Math.max(0,pad.pt/mt);cx.fillStyle=col;cx.fillRect(pad.x,pad.y+PAD_H+2,pad.w*ratio,3);}
}

function updBall(dt){
  if(ball.slowed){ball.st-=dt;if(ball.st<=0){ball.vx/=0.55;ball.vy/=0.55;ball.slowed=false;}}
  ball.trail.push({x:ball.x,y:ball.y});
  if(ball.trail.length>10) ball.trail.shift();
  ball.x+=ball.vx; ball.y+=ball.vy;
  if(ball.x-BALL_R<0){ball.x=BALL_R;ball.vx=Math.abs(ball.vx);}
  if(ball.x+BALL_R>W){ball.x=W-BALL_R;ball.vx=-Math.abs(ball.vx);}
  if(ball.y-BALL_R<HUD){ball.y=HUD+BALL_R;ball.vy=Math.abs(ball.vy);}
  if(ball.y-BALL_R>H) return{destroyed:[],lost:true};
  if(ball.vy>0&&overlap(ball.x-BALL_R,ball.y-BALL_R,BALL_R*2,BALL_R*2,pad.x,pad.y,pad.w,PAD_H)){
    ball.y=pad.y-BALL_R;
    const hr=(ball.x-pad.x)/pad.w;
    const ang=(hr-0.5)*2*65*Math.PI/180;
    const spd=Math.hypot(ball.vx,ball.vy);
    ball.vx=spd*Math.sin(ang); ball.vy=-spd*Math.cos(ang);
    const minVy=spd*0.3;
    if(Math.abs(ball.vy)<minVy){ball.vy=-minVy;ball.vx=Math.sign(ball.vx)*Math.sqrt(Math.max(0,spd*spd-minVy*minVy));}
    combo=0;
  }
  const destroyed=[];
  for(const b of bricks){
    if(!b.alive) continue;
    if(!overlap(ball.x-BALL_R,ball.y-BALL_R,BALL_R*2,BALL_R*2,b.x,b.y,BW,BH)) continue;
    const ol=ball.x+BALL_R-b.x,or2=b.x+BW-(ball.x-BALL_R);
    const ot=ball.y+BALL_R-b.y,ob=b.y+BH-(ball.y-BALL_R);
    const m=Math.min(ol,or2,ot,ob);
    if(m===ot&&ball.vy>0){ball.vy=-Math.abs(ball.vy);ball.y=b.y-BALL_R;}
    else if(m===ob&&ball.vy<0){ball.vy=Math.abs(ball.vy);ball.y=b.y+BH+BALL_R;}
    else if(m===ol&&ball.vx>0){ball.vx=-Math.abs(ball.vx);ball.x=b.x-BALL_R;}
    else{ball.vx=Math.abs(ball.vx);ball.x=b.x+BW+BALL_R;}
    b.ft=0.12;
    if(b.type!=='steel'){b.hp--;if(b.hp<=0){b.alive=false;destroyed.push(b);}}
    break;
  }
  return{destroyed,lost:false};
}
function drawBall(){
  const n=ball.trail.length;
  ball.trail.forEach((t,i)=>{
    const a=Math.floor(180*(i+1)/n);
    const r=Math.max(2,Math.round(BALL_R*(i+1)/n));
    cx.globalAlpha=a/255; cx.beginPath(); cx.arc(t.x,t.y,r,0,Math.PI*2);
    cx.fillStyle='#00dcff'; cx.fill();
  });
  cx.globalAlpha=1;
  cx.beginPath();cx.arc(ball.x,ball.y,BALL_R,0,Math.PI*2);cx.fillStyle='#ffffff';cx.fill();
  cx.beginPath();cx.arc(ball.x-2,ball.y-2,Math.max(1,BALL_R/3),0,Math.PI*2);cx.fillStyle='#d2ebff';cx.fill();
}
function drawBrick(b){
  if(!b.alive) return;
  const base=b.type==='steel'?BCOLORS.steel:BCOLORS[Math.min(b.hp,3)]||BCOLORS[1];
  const col=b.ft>0?'#ffffff':base;
  rr(b.x,b.y,BW,BH,4,col,'#141423',1.5);
  if(b.type==='normal'&&b.maxHp>1&&b.maxHp<90){
    const dr=3,total=b.hp*(dr*2+2)-2,sx=b.x+BW/2-total/2,cy2=b.y+BH/2;
    for(let i=0;i<b.hp;i++){cx.beginPath();cx.arc(sx+i*(dr*2+2)+dr,cy2,dr,0,Math.PI*2);cx.fillStyle='white';cx.fill();}
  }
  if(b.type==='steel'){
    const gcx=b.x+BW/2,gcy=b.y+BH/2;
    [[-5,0],[5,0],[0,-4],[0,4]].forEach(([ox,oy])=>{cx.beginPath();cx.arc(gcx+ox,gcy+oy,2,0,Math.PI*2);cx.fillStyle='white';cx.fill();});
  }
}
function drawPU(p){
  const col=PUCOLORS[p.type],lbl=PULABELS[p.type];
  const pulse=1+0.1*Math.sin(p.anim*5),pr=Math.round(18*pulse);
  cx.beginPath();cx.arc(p.x,p.y,pr,0,Math.PI*2);cx.fillStyle=col;cx.fill();
  cx.strokeStyle='#141423';cx.lineWidth=1.5;cx.stroke();
  cx.fillStyle='white';cx.font='bold 11px monospace';cx.textAlign='center';cx.textBaseline='middle';
  cx.fillText(lbl,p.x,p.y);
}
function drawHud(){
  cx.fillStyle='#0f0f23';cx.fillRect(0,0,W,HUD);
  cx.strokeStyle='#00dcff44';cx.lineWidth=1;cx.beginPath();cx.moveTo(0,HUD-1);cx.lineTo(W,HUD-1);cx.stroke();
  cx.fillStyle='white';cx.font='bold 15px monospace';cx.textAlign='left';cx.textBaseline='middle';
  cx.fillText('SCORE '+String(score).padStart(7,'0'),12,HUD/2);
  cx.fillStyle='#00dcff';cx.textAlign='center';
  cx.fillText('NIVEL '+lv,W/2,HUD/2);
  for(let i=0;i<lives;i++) drawHeart(W-22-i*22,HUD/2,8,'#ff64b4');
  if(combo>1){const mult=1+Math.floor(combo/3)*0.5;cx.fillStyle=mult>1?'#ffc832':'#ffdc00';cx.font='bold 12px monospace';cx.textAlign='right';cx.fillText('x'+combo+' ('+mult.toFixed(1)+'x)',W-22-lives*22-8,HUD/2);}
}
function drawHeart(hcx,hcy,size,color){
  const r=Math.floor(size/2);cx.fillStyle=color;
  cx.beginPath();cx.arc(hcx-r,hcy-r/2,r,0,Math.PI*2);cx.fill();
  cx.beginPath();cx.arc(hcx+r,hcy-r/2,r,0,Math.PI*2);cx.fill();
  cx.beginPath();cx.moveTo(hcx-size,hcy-r/2);cx.lineTo(hcx+size,hcy-r/2);cx.lineTo(hcx,hcy+size-2);cx.closePath();cx.fill();
}
function drawOverlay(a){cx.fillStyle='rgba(0,0,12,'+a+')';cx.fillRect(0,0,W,H);}
function menuBtn(i,label){
  const bx=W/2-110,by=H/2+10+i*58,bw=220,bh=44;
  rr(bx,by,bw,bh,7,'#3c3c64','#00dcff',1.5);
  cx.fillStyle='white';cx.font='bold 17px monospace';cx.textAlign='center';cx.textBaseline='middle';
  cx.fillText(label,bx+bw/2,by+bh/2);
}
function endBtn(side,label){
  const bx=side==='left'?W/2-230:W/2+20,by=H/2+100,bw=200,bh=44;
  rr(bx,by,bw,bh,7,'#3c3c64','#00dcff',1.5);
  cx.fillStyle='white';cx.font='bold 15px monospace';cx.textAlign='center';cx.textBaseline='middle';
  cx.fillText(label,bx+bw/2,by+bh/2);
}
function drawStars(){stars.forEach(s=>{cx.fillStyle='rgb('+s.b+','+s.b+','+s.b+')';if(s.s===1){cx.fillRect(Math.round(s.x),Math.round(s.y),1,1);}else{cx.beginPath();cx.arc(s.x,s.y,s.s,0,Math.PI*2);cx.fill();}});}

let last=performance.now();
function loop(ts){
  requestAnimationFrame(loop);
  const dt=Math.min((ts-last)/1000,0.05);last=ts;
  tt+=dt;at+=dt;
  cx.fillStyle='#0a0a18';cx.fillRect(0,0,W,H);
  stars.forEach(s=>{s.y+=s.spd;if(s.y>H){s.y=0;s.x=Math.random()*W;}});
  drawStars();

  if(ST==='menu'){
    drawOverlay(0.65);
    const hue=(Math.sin(tt*1.5)+1)/2;
    const tc=lerpC([0,220,255],[220,0,255],hue);
    cx.font='bold 52px monospace';cx.textAlign='center';cx.textBaseline='top';
    cx.fillStyle='#1a1a40';cx.fillText('BRICKSTORM',W/2+3,H/2-200+3);
    cx.fillStyle='rgb('+tc[0]+','+tc[1]+','+tc[2]+')';cx.fillText('BRICKSTORM',W/2,H/2-200);
    cx.fillStyle='#8c8cb4';cx.font='13px monospace';cx.fillText('Arkanoid Edition',W/2,H/2-200+62);
    ['Jugar','Instrucciones','Creditos','Salir'].forEach((l,i)=>menuBtn(i,l));

  } else if(ST==='instructions'){
    drawOverlay(0.88);
    [['INSTRUCCIONES','bold 30px monospace','#00dcff',40],
     ['CONTROLES','bold 20px monospace','#ffdc00',90],
     ['Flechas / A D   mover paleta','15px monospace','white',120],
     ['ESPACIO   lanzar pelota','15px monospace','white',143],
     ['P   pausar/reanudar','15px monospace','white',166],
     ['R   reiniciar nivel','15px monospace','white',189],
     ['ESC   menu','15px monospace','white',212],
     ['POWER-UPS','bold 20px monospace','#ffdc00',250],
     ['+W verde   amplia paleta','15px monospace','#32dc50',280],
     ['SL cyan   ralentiza pelota','15px monospace','#00dcff',303],
     ['+1 rosa   vida extra','15px monospace','#ff64b4',326],
     ['-W rojo   encoge paleta','15px monospace','#ff3232',349],
     ['LADRILLOS: Azul=1  Naranja=2  Rojo=3','15px monospace','white',390],
     ['Gris = acero indestructible','15px monospace','#8c96aa',413],
     ['ESC para volver','13px monospace','#556',480]
    ].forEach(([t,f,c,y])=>ct(t,f,c,y));

  } else if(ST==='credits'){
    drawOverlay(0.88);
    [['CREDITOS','bold 30px monospace','#00dcff',60],
     ['Proyecto academico','bold 18px monospace','#ffdc00',120],
     ['Adaptado a JavaScript Canvas','15px monospace','white',150],
     ['Inspirado en Arkanoid (Taito 1986)','15px monospace','white',200],
     ['y Breakout (Atari 1976)','15px monospace','white',223],
     ['ESC para volver','13px monospace','#556',350]
    ].forEach(([t,f,c,y])=>ct(t,f,c,y));

  } else if(['launching','playing','paused','level_complete'].includes(ST)){
    bricks.forEach(b=>{if(b.ft>0)b.ft=Math.max(0,b.ft-dt);drawBrick(b);});
    pups.forEach(drawPU);
    drawBall(); drawPad(); drawHud();

    if(ST==='launching'){
      ball.x=pad.x+pad.w/2; ball.y=pad.y-BALL_R-1; ball.trail=[];
      cx.fillStyle='rgba(160,160,200,0.8)';cx.font='14px monospace';cx.textAlign='center';cx.textBaseline='bottom';
      cx.fillText('ESPACIO o clic para lanzar',W/2,H-8);
    } else if(ST==='playing'){
      updPad(dt);
      const{destroyed,lost}=updBall(dt);
      if(lost){
        lives--;combo=0;pups=[];
        if(lives<=0){ST='gameover';}
        else{
          pad={x:(W-PAD_BASE)/2,y:PAD_Y,w:PAD_BASE,pw:null,pt:0};
          const spd=4.5+(lv-1)*0.5;
          const ang=(Math.random()*80-40)*Math.PI/180;
          ball={x:pad.x+PAD_BASE/2,y:pad.y-BALL_R-1,vx:spd*Math.sin(ang),vy:-spd*Math.cos(ang),trail:[],slowed:false,st:0};
          ST='launching';
        }
      } else {
        destroyed.forEach(b=>{
          combo++;maxCombo=Math.max(maxCombo,combo);
          const mult=1+Math.floor(combo/3)*0.5;
          score+=Math.round((b.maxHp>10?1:b.maxHp)*50*mult);
          if(Math.random()<0.3){
            const types=['expand','slow','life','shrink'];
            pups.push({x:b.x+BW/2,y:b.y+BH/2,type:types[Math.floor(Math.random()*4)],active:true,anim:0});
          }
        });
        pups.forEach(p=>{
          p.y+=2;p.anim+=dt;if(p.y>H)p.active=false;
          if(p.active&&overlap(p.x-16,p.y-16,32,32,pad.x,pad.y,pad.w,PAD_H)){
            if(p.type==='expand'||p.type==='shrink') applyPadPU(p.type);
            else if(p.type==='slow'&&!ball.slowed){ball.vx*=0.55;ball.vy*=0.55;ball.slowed=true;ball.st=6;}
            else if(p.type==='life') lives=Math.min(6,lives+1);
            p.active=false;
          }
        });
        pups=pups.filter(p=>p.active);
        if(!bricks.some(b=>b.alive&&b.type!=='steel')){ST='level_complete';msgT=2.2;}
      }
    } else if(ST==='level_complete'){
      msgT-=dt;if(msgT<=0){lv++;if(lv>3)ST='victory';else loadLv();}
      drawOverlay(0.6);
      ct('NIVEL '+lv+' SUPERADO','bold 34px monospace','#32dc50',H/2-50);
      ct('Preparando nivel '+lv+'...','16px monospace','white',H/2+10);
    } else if(ST==='paused'){
      drawOverlay(0.6);
      ct('PAUSA','bold 36px monospace','#ffdc00',H/2-50);
      ct('P reanudar  |  R reiniciar  |  ESC menu','15px monospace','white',H/2+10);
    }

  } else if(ST==='gameover'){
    bricks.forEach(b=>{if(b.ft>0)b.ft=Math.max(0,b.ft-dt);drawBrick(b);});
    pups.forEach(drawPU);drawBall();drawPad();drawHud();
    drawOverlay(0.75);
    ct('GAME OVER','bold 56px monospace','#ff3250',H/2-130);
    ct('Puntuacion: '+String(score).padStart(7,'0'),'bold 22px monospace','white',H/2-40);
    endBtn('left','Reiniciar');endBtn('right','Menu');

  } else if(ST==='victory'){
    bricks.forEach(b=>{if(b.ft>0)b.ft=Math.max(0,b.ft-dt);drawBrick(b);});
    pups.forEach(drawPU);drawBall();drawPad();drawHud();
    drawOverlay(0.75);
    const hue2=(Math.sin(at*2)+1)/2;
    const vc=lerpC([0,220,255],[255,200,50],hue2);
    cx.font='bold 56px monospace';cx.textAlign='center';cx.textBaseline='top';
    cx.fillStyle='rgb('+vc[0]+','+vc[1]+','+vc[2]+')';
    cx.fillText('VICTORIA!',W/2,H/2-130);
    ct('Puntuacion: '+String(score).padStart(7,'0'),'bold 22px monospace','white',H/2-40);
    ct('Combo maximo: x'+maxCombo,'bold 20px monospace','#ffc832',H/2-8);
    endBtn('left','Reiniciar');endBtn('right','Menu');
  }
}
requestAnimationFrame(loop);
})();
</script>
"""

display(HTML(html))