# -*- coding: utf-8 -*-
"""calculadora.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xyx4GGM-i2Z9qkQjXJlBtX8iRsXyI4WN
"""

class Prestamo:
    def __init__(self, monto, tasa, plazo):
        self.monto = monto
        self.tasa = tasa / 100
        self.plazo = plazo

    def simple(self):
        ganancia = self.monto * self.tasa * self.plazo
        total = self.monto + ganancia
        return ganancia, total

    def compuesto(self):
        total = self.monto * (1 + self.tasa) ** self.plazo
        ganancia = total - self.monto
        return ganancia, total


def main():
    print("=== CALCULADORA DE INTERESES ===")
    monto = float(input("Monto inicial ($): "))
    tasa = float(input("Tasa anual (%): "))
    plazo = float(input("Plazo en años: "))

    p = Prestamo(monto, tasa, plazo)

    simple = p.simple()
    compuesto = p.compuesto()

    print("\n-- Interés Simple --")
    print(f"Interés: ${simple[0]:.2f}")
    print(f"Total:   ${simple[1]:.2f}")

    print("\n-- Interés Compuesto --")
    print(f"Interés: ${compuesto[0]:.2f}")
    print(f"Total:   ${compuesto[1]:.2f}")


main()