# -*- coding: utf-8 -*-
"""estructura de seleccion.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NaLgqSK2dKpU2SmkBglYIXlbgJeNJ4og

ESTRUCTURA DE SELECCION
Evaluan una condicion de verdad
1.IF/ELSE
2.IF TERNARIO
3.IF/ELIF/ELSE
4.CASE

1.IF/ELSE Solo tiene dos posibles respuesta(V) (F) sintaxis
if (condicion)
#aqui se ejecuta codigo si la condicon es verdadera

else:
  #aqui se ejecuta el codiog si la condicion es falsa
"""

lluvia = input("¿Está lloviendo? ")

if lluvia == "no":
    print("Te recomiendo ir al parque")
elif lluvia == "un poco":
    print("Te sugiero ir con sombrilla")
elif lluvia == "si":
    print("Cierra las ventanas")
else:
    print("Resguardarse")