# -*- coding: utf-8 -*-
"""flor.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CVJ7wYAk9SsxNI1wzp_XNUSyd8_rJwrX
"""

from IPython.display import HTML

html_code = """
<!DOCTYPE html>
<html>
<head>
  <style>
    body { margin: 0; background: #000; overflow: hidden; }
    #c { width: 100%; height: 500px; display: block; }
    .controls {
      position: fixed; bottom: 10px; left: 0; right: 0;
      display: flex; justify-content: center; gap: 12px; flex-wrap: wrap;
    }
    .ctrl {
      display: flex; align-items: center; gap: 6px;
      background: rgba(0,0,0,0.6); border-radius: 20px; padding: 5px 12px;
    }
    label, span { font-size: 12px; color: #fff; font-family: sans-serif; }
  </style>
</head>
<body>
<canvas id="c"></canvas>
<div class="controls">
  <div class="ctrl">
    <label>Pétalos</label>
    <input type="range" id="petals" min="5" max="24" value="16" step="1" style="width:70px;">
    <span id="petals-out">16</span>
  </div>
  <div class="ctrl">
    <label>Capas</label>
    <input type="range" id="layers" min="4" max="20" value="12" step="1" style="width:70px;">
    <span id="layers-out">12</span>
  </div>
  <div class="ctrl">
    <label>Velocidad</label>
    <input type="range" id="speed" min="1" max="10" value="4" step="1" style="width:70px;">
  </div>
</div>

<script src="https://cdnjs.cloudflare.com/ajax/libs/three.js/r128/three.min.js"></script>
<script>
const canvas = document.getElementById('c');
const renderer = new THREE.WebGLRenderer({ canvas, antialias: true });
renderer.setPixelRatio(window.devicePixelRatio);
renderer.setClearColor(0x000000, 1);

const scene = new THREE.Scene();
const camera = new THREE.PerspectiveCamera(45, canvas.clientWidth / canvas.clientHeight, 0.1, 1000);
camera.position.set(0, 3, 7);
camera.lookAt(0, 0, 0);

scene.add(new THREE.AmbientLight(0xffffff, 0.4));
const dirLight = new THREE.DirectionalLight(0xffffff, 0.9);
dirLight.position.set(5, 10, 5);
scene.add(dirLight);
const backLight = new THREE.DirectionalLight(0xffffff, 0.3);
backLight.position.set(-5, -3, -5);
scene.add(backLight);

const flowerGroup = new THREE.Group();
scene.add(flowerGroup);

function hsvToRgb(h, s, v) {
  const i = Math.floor(h * 6);
  const f = h * 6 - i;
  const p = v*(1-s), q = v*(1-f*s), t = v*(1-(1-f)*s);
  let r, g, b;
  switch(i % 6){
    case 0: r=v;g=t;b=p;break; case 1: r=q;g=v;b=p;break;
    case 2: r=p;g=v;b=t;break; case 3: r=p;g=q;b=v;break;
    case 4: r=t;g=p;b=v;break; case 5: r=v;g=p;b=q;break;
  }
  return new THREE.Color(r, g, b);
}

function buildFlower(numPetals, numLayers) {
  while(flowerGroup.children.length) {
    const c = flowerGroup.children[0];
    if(c.geometry) c.geometry.dispose();
    if(c.material) c.material.dispose();
    flowerGroup.remove(c);
  }
  let h = 0;
  const hStep = 1 / (numPetals * numLayers);
  for(let i = 0; i < numPetals; i++) {
    const petalAngle = (i / numPetals) * Math.PI * 2;
    for(let j = 0; j < numLayers; j++) {
      const t = j / numLayers;
      const layerRadius = 0.3 + t * 2.2;
      const petalLen = 0.8 + (1 - t) * 1.4;
      const petalW = 0.18 + (1 - t) * 0.32;
      const lift = Math.sin(t * Math.PI) * 0.8 + t * 0.2;
      const tilt = t * 0.6;
      const shape = new THREE.Shape();
      shape.moveTo(0, 0);
      shape.bezierCurveTo(-petalW, petalLen*0.3, -petalW*0.8, petalLen*0.7, 0, petalLen);
      shape.bezierCurveTo(petalW*0.8, petalLen*0.7, petalW, petalLen*0.3, 0, 0);
      const geo = new THREE.ExtrudeGeometry(shape, {
        depth: petalW*0.3, bevelEnabled:true,
        bevelThickness:0.03, bevelSize:0.03, bevelSegments:3
      });
      const color = hsvToRgb(h, 0.85, 1.0);
      h = (h + hStep) % 1;
      const mat = new THREE.MeshPhongMaterial({
        color, emissive: color.clone().multiplyScalar(0.15),
        shininess: 80, side: THREE.DoubleSide
      });
      const mesh = new THREE.Mesh(geo, mat);
      mesh.rotation.x = -Math.PI/2 + tilt;
      mesh.rotation.y = -petalAngle;
      mesh.position.set(Math.cos(petalAngle)*layerRadius, lift, Math.sin(petalAngle)*layerRadius);
      flowerGroup.add(mesh);
    }
  }
  const stem = new THREE.Mesh(
    new THREE.CylinderGeometry(0.06, 0.1, 2.5, 10),
    new THREE.MeshPhongMaterial({ color: 0x2e7d32 })
  );
  stem.position.y = -1.25;
  flowerGroup.add(stem);
  const center = new THREE.Mesh(
    new THREE.SphereGeometry(0.35, 16, 16),
    new THREE.MeshPhongMaterial({ color: 0xf9a825, emissive: 0x5d4037, shininess: 120 })
  );
  center.position.y = 0.15;
  flowerGroup.add(center);
}

let numPetals = 16, numLayers = 12;
buildFlower(numPetals, numLayers);

renderer.setSize(canvas.clientWidth, canvas.clientHeight);

let isDragging = false, prevX = 0, prevY = 0, rotX = 0.3, rotY = 0;
canvas.addEventListener('mousedown', e => { isDragging=true; prevX=e.clientX; prevY=e.clientY; });
window.addEventListener('mouseup', () => isDragging=false);
canvas.addEventListener('mousemove', e => {
  if(!isDragging) return;
  rotY += (e.clientX-prevX)*0.01;
  rotX += (e.clientY-prevY)*0.01;
  rotX = Math.max(-1.2, Math.min(1.2, rotX));
  prevX=e.clientX; prevY=e.clientY;
});

document.getElementById('petals').oninput = function() {
  numPetals = +this.value;
  document.getElementById('petals-out').textContent = numPetals;
  buildFlower(numPetals, numLayers);
};
document.getElementById('layers').oninput = function() {
  numLayers = +this.value;
  document.getElementById('layers-out').textContent = numLayers;
  buildFlower(numPetals, numLayers);
};

let autoRotY = 0;
function animate() {
  requestAnimationFrame(animate);
  const spd = +document.getElementById('speed').value * 0.003;
  if(!isDragging) autoRotY += spd;
  flowerGroup.rotation.y = autoRotY + rotY;
  flowerGroup.rotation.x = rotX;
  renderer.render(scene, camera);
}
animate();
</script>
</body>
</html>
"""

HTML(html_code)