# -*- coding: utf-8 -*-
"""JAVA_EDAD.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Brch_CnpUw6wJRVTMWJnAtHPqaxIszVb
"""

import java.util.*;
public class Main
{
	public static void main(String[] args) {
		System.out.println("Cuál es tu edad");
		Scanner leer = new Scanner(System.in);
		int edad = leer.nextInt();
		System.out.println(edad>=18? "Eres mayor de edad ": "Eres menor de edad ");
	}
}