# -*- coding: utf-8 -*-
"""java 2ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iKyCCCtQnB78qv156bPVdAf-FatVOaT-
"""

/******************************************************************************

                            Online Java Compiler.
                Code, Compile, Run and Debug java program online.
Write your code in this editor and press "Run" button to execute it.

*******************************************************************************/

import java.util.Scanner;

public class Main {
    public static void main(String[] args) {
        Scanner sc = new Scanner(System.in);
        int[] votos = new int[5];

        System.out.print("Número de votantes: ");
        int n = sc.nextInt();

        for (int i = 0; i < n; i++) {
            System.out.print("Candidato (1-5): ");
            votos[sc.nextInt() - 1]++;
        }

        int p1 = 0, p2 = 0, c1 = 0, c2 = 0;
        for (int i = 0; i < 5; i++) {
            System.out.println("Candidato " + (i+1) + ": " + votos[i] + " votos");
            if (votos[i] > p1) { p2=p1; c2=c1; p1=votos[i]; c1=i; }
            else if (votos[i] > p2) { p2=votos[i]; c2=i; }
        }

        System.out.println("Segunda vuelta: " + (c1+1) + " vs " + (c2+1));
        int v1 = 0, v2 = 0;
        for (int i = 0; i < n; i++) {
            System.out.print("Vote 1 o 2: ");
            if (sc.nextInt() == 1) v1++; else v2++;
        }

        System.out.println("Ganador: Candidato " + (v1 > v2 ? c1+1 : c2+1));
    }
}