# -*- coding: utf-8 -*-
"""juegoMAINQUEST.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1b8tcWNcBa8nzOTs7XVFOGOtf217i4ttI
"""

from IPython.display import display, HTML

HTML_JUEGO = """
<!DOCTYPE html>
<html lang="es">
<head>
<meta charset="UTF-8">
<style>
  * { box-sizing: border-box; margin: 0; padding: 0; }
  body {
    font-family: 'Segoe UI', sans-serif;
    background: linear-gradient(135deg, #1a1a2e 0%, #16213e 50%, #0f3460 100%);
    min-height: 100vh;
    display: flex;
    align-items: center;
    justify-content: center;
    padding: 20px;
  }
  .card {
    background: rgba(255,255,255,0.05);
    border: 1px solid rgba(255,255,255,0.1);
    border-radius: 24px;
    padding: 40px;
    max-width: 620px;
    width: 100%;
    color: white;
  }
  h1 {
    font-size: 28px;
    font-weight: 700;
    text-align: center;
    margin-bottom: 6px;
    background: linear-gradient(90deg, #a78bfa, #60a5fa);
    -webkit-background-clip: text;
    -webkit-text-fill-color: transparent;
  }
  .subtitle { text-align: center; color: rgba(255,255,255,0.5); font-size: 14px; margin-bottom: 32px; }
  .progress-bar { background: rgba(255,255,255,0.1); border-radius: 99px; height: 6px; margin-bottom: 32px; overflow: hidden; }
  .progress-fill { background: linear-gradient(90deg, #a78bfa, #60a5fa); height: 100%; border-radius: 99px; transition: width 0.4s ease; }
  .pregunta-num { font-size: 12px; color: rgba(255,255,255,0.4); margin-bottom: 12px; text-transform: uppercase; letter-spacing: 1px; }
  .pregunta-texto { font-size: 20px; font-weight: 600; margin-bottom: 28px; line-height: 1.4; }
  .opciones { display: flex; flex-direction: column; gap: 12px; }
  .opcion {
    background: rgba(255,255,255,0.07);
    border: 1px solid rgba(255,255,255,0.12);
    border-radius: 14px;
    padding: 18px 20px;
    cursor: pointer;
    transition: all 0.2s;
    font-size: 15px;
    color: white;
    text-align: left;
    display: flex;
    align-items: center;
    gap: 14px;
  }
  .opcion:hover { background: rgba(167,139,250,0.2); border-color: rgba(167,139,250,0.5); transform: translateX(4px); }
  .opcion-letra { background: rgba(255,255,255,0.1); border-radius: 8px; width: 32px; height: 32px; display: flex; align-items: center; justify-content: center; font-weight: 700; font-size: 13px; flex-shrink: 0; }
  .resultado { text-align: center; display: none; }
  .mbti-tipo { font-size: 64px; font-weight: 900; background: linear-gradient(90deg, #a78bfa, #60a5fa, #34d399); -webkit-background-clip: text; -webkit-text-fill-color: transparent; margin-bottom: 8px; line-height: 1; }
  .mbti-nombre { font-size: 22px; font-weight: 600; margin-bottom: 20px; color: rgba(255,255,255,0.9); }
  .mbti-imagen { width: 180px; height: 180px; border-radius: 50%; margin: 0 auto 24px; display: flex; align-items: center; justify-content: center; font-size: 72px; border: 3px solid rgba(167,139,250,0.4); background: rgba(255,255,255,0.05); }
  .mbti-desc { font-size: 15px; color: rgba(255,255,255,0.7); line-height: 1.7; margin-bottom: 28px; background: rgba(255,255,255,0.05); border-radius: 14px; padding: 20px; text-align: left; }
  .dimensiones { display: grid; grid-template-columns: 1fr 1fr; gap: 10px; margin-bottom: 28px; }
  .dim-card { background: rgba(255,255,255,0.06); border: 1px solid rgba(255,255,255,0.1); border-radius: 12px; padding: 14px; text-align: center; }
  .dim-letra { font-size: 28px; font-weight: 700; color: #a78bfa; }
  .dim-nombre { font-size: 11px; color: rgba(255,255,255,0.4); margin-top: 2px; }
  .btn-reiniciar { background: linear-gradient(90deg, #a78bfa, #60a5fa); border: none; border-radius: 12px; color: white; font-size: 15px; font-weight: 600; padding: 14px 32px; cursor: pointer; }
  .pantalla-inicio { text-align: center; }
  .btn-iniciar { background: linear-gradient(90deg, #a78bfa, #60a5fa); border: none; border-radius: 12px; color: white; font-size: 16px; font-weight: 600; padding: 16px 40px; cursor: pointer; margin-top: 24px; }
  .intro-desc { color: rgba(255,255,255,0.6); font-size: 15px; line-height: 1.7; margin-top: 16px; }
  .emoji-grande { font-size: 56px; margin-bottom: 16px; }
</style>
</head>
<body>
<div class="card">
  <div id="pantalla-inicio" class="pantalla-inicio">
    <div class="emoji-grande">🧠</div>
    <h1>Test de Personalidad</h1>
    <p class="subtitle">Descubre tu tipo MBTI</p>
    <p class="intro-desc">Responde 8 preguntas honestas sobre cómo eres normalmente.<br>Al final descubrirás cuál de los 16 tipos de personalidad eres.</p>
    <button class="btn-iniciar" onclick="iniciar()">Comenzar test</button>
  </div>
  <div id="pantalla-preguntas" style="display:none;">
    <div class="progress-bar"><div class="progress-fill" id="progreso" style="width:0%"></div></div>
    <p class="pregunta-num" id="num-pregunta"></p>
    <p class="pregunta-texto" id="texto-pregunta"></p>
    <div class="opciones" id="opciones"></div>
  </div>
  <div id="pantalla-resultado" class="resultado">
    <div class="mbti-imagen" id="emoji-resultado"></div>
    <div class="mbti-tipo" id="tipo-resultado"></div>
    <div class="mbti-nombre" id="nombre-resultado"></div>
    <div class="dimensiones" id="dimensiones-resultado"></div>
    <div class="mbti-desc" id="desc-resultado"></div>
    <button class="btn-reiniciar" onclick="reiniciar()">Volver a intentarlo</button>
  </div>
</div>
<script>
class Pregunta {
  constructor(texto, opcionA, opcionB, letraA, letraB) {
    this.texto = texto; this.opcionA = opcionA; this.opcionB = opcionB; this.letraA = letraA; this.letraB = letraB;
  }
}
class TipoMBTI {
  constructor(codigo, nombre, emoji, descripcion, dims) {
    this.codigo = codigo; this.nombre = nombre; this.emoji = emoji; this.descripcion = descripcion; this.dims = dims;
  }
}
class JuegoMBTI {
  constructor() {
    this.preguntas = [
      new Pregunta("En una fiesta o reunión social tú...","Hablas con muchas personas y disfrutas el ambiente.","Prefieres quedarte con una o dos personas conocidas.","E","I"),
      new Pregunta("Después de un día muy social te sientes...","Con energía y ganas de más.","Agotado y necesitando tiempo solo para recargar.","E","I"),
      new Pregunta("Al aprender algo nuevo prefieres...","Ejemplos concretos y pasos claros.","Entender la idea general y el concepto primero.","S","N"),
      new Pregunta("Confías más en...","Lo que puedes ver, tocar y comprobar.","Tu intuición y corazonadas.","S","N"),
      new Pregunta("Al tomar decisiones importantes te guías más por...","La lógica y los datos.","Cómo va a afectar a las personas involucradas.","T","F"),
      new Pregunta("Cuando un amigo tiene un problema, tú...","Le das consejos prácticos para resolverlo.","Lo escuchas y le das apoyo emocional.","T","F"),
      new Pregunta("Tu cuarto o escritorio suele estar...","Organizado, cada cosa en su lugar.","Un poco caótico, pero tú sabes dónde está todo.","J","P"),
      new Pregunta("Cuando tienes un proyecto prefieres...","Planificarlo todo antes de empezar.","Ir viendo cómo sale sobre la marcha.","J","P"),
    ];
    this.tipos = {
      "INTJ": new TipoMBTI("INTJ","El Arquitecto","🏛️","Eres estratégico, independiente y con una visión clara del futuro. Planeas todo con precisión y confías en tu mente analítica para resolver problemas complejos.",["Introvertido","Intuitivo","Lógico","Planificador"]),
      "INTP": new TipoMBTI("INTP","El Lógico","🔬","Eres curioso, analítico y amante de las ideas abstractas. Te encanta encontrar patrones y construir teorías. Prefieres la precisión al consenso social.",["Introvertido","Intuitivo","Lógico","Espontáneo"]),
      "ENTJ": new TipoMBTI("ENTJ","El Comandante","⚔️","Eres un líder nato, directo, ambicioso y eficiente. Ves el camino hacia el éxito y no dudas en tomar decisiones difíciles para llegar ahí.",["Extrovertido","Intuitivo","Lógico","Planificador"]),
      "ENTP": new TipoMBTI("ENTP","El Innovador","💡","Eres ingenioso, curioso y amas los debates. Encuentras soluciones creativas donde otros no ven nada y disfrutas desafiar ideas establecidas.",["Extrovertido","Intuitivo","Lógico","Espontáneo"]),
      "INFJ": new TipoMBTI("INFJ","El Defensor","🌙","Eres empático, visionario y profundo. Tienes una conexión única con las emociones ajenas y una visión clara de cómo mejorar el mundo.",["Introvertido","Intuitivo","Empático","Planificador"]),
      "INFP": new TipoMBTI("INFP","El Mediador","🌸","Eres soñador, creativo y fiel a tus valores. Buscas autenticidad en todo y tienes una riqueza emocional interior enorme que pocas personas ven.",["Introvertido","Intuitivo","Empático","Espontáneo"]),
      "ENFJ": new TipoMBTI("ENFJ","El Protagonista","🌟","Eres carismático, inspirador y altruista. Naturalmente motivas a los demás y tienes un talento especial para ver el potencial en cada persona.",["Extrovertido","Intuitivo","Empático","Planificador"]),
      "ENFP": new TipoMBTI("ENFP","El Activista","🎨","Eres entusiasta, creativo y sociable. Ves posibilidades en todo y contagias tu energía a quienes te rodean. Detestas la rutina.",["Extrovertido","Intuitivo","Empático","Espontáneo"]),
      "ISTJ": new TipoMBTI("ISTJ","El Logístico","📋","Eres responsable, ordenado y confiable. Cumples con tus compromisos sin importar las circunstancias y valoras la tradición y la estabilidad.",["Introvertido","Sensorial","Lógico","Planificador"]),
      "ISFJ": new TipoMBTI("ISFJ","El Protector","🛡️","Eres dedicado, cálido y detallista. Siempre estás ahí para los demás y te aseguras de que todos estén bien, a veces antes que tú mismo.",["Introvertido","Sensorial","Empático","Planificador"]),
      "ESTJ": new TipoMBTI("ESTJ","El Ejecutivo","📌","Eres organizado, práctico y decidido. Sabes cómo gestionar personas y proyectos, y no tienes miedo de tomar el control cuando nadie más lo hace.",["Extrovertido","Sensorial","Lógico","Planificador"]),
      "ESFJ": new TipoMBTI("ESFJ","El Cónsul","🤝","Eres sociable, leal y siempre pendiente de los demás. Creas armonía en tu entorno y te esfuerzas porque todos estén cómodos y felices.",["Extrovertido","Sensorial","Empático","Planificador"]),
      "ISTP": new TipoMBTI("ISTP","El Virtuoso","🔧","Eres observador, práctico y reservado. Te encanta entender cómo funcionan las cosas y resolver problemas con tus propias manos.",["Introvertido","Sensorial","Lógico","Espontáneo"]),
      "ISFP": new TipoMBTI("ISFP","El Aventurero","🎭","Eres flexible, encantador y artístico. Vives el momento y tienes una sensibilidad estética especial. Odias los conflictos y las restricciones.",["Introvertido","Sensorial","Empático","Espontáneo"]),
      "ESTP": new TipoMBTI("ESTP","El Emprendedor","⚡","Eres energético, directo y observador. Actúas rápido, piensas en el momento y te encanta la acción. Eres el primero en lanzarse al reto.",["Extrovertido","Sensorial","Lógico","Espontáneo"]),
      "ESFP": new TipoMBTI("ESFP","El Animador","🎉","Eres espontáneo, divertido y sociable. Donde tú estás hay buena vibra. Vives el presente al máximo y sabes cómo hacer que todos la pasen bien.",["Extrovertido","Sensorial","Empático","Espontáneo"]),
    };
    this.puntaje = { E:0, I:0, S:0, N:0, T:0, F:0, J:0, P:0 };
    this.indice = 0;
  }
  calcularTipo() {
    let t = "";
    t += this.puntaje.E >= this.puntaje.I ? "E" : "I";
    t += this.puntaje.S >= this.puntaje.N ? "S" : "N";
    t += this.puntaje.T >= this.puntaje.F ? "T" : "F";
    t += this.puntaje.J >= this.puntaje.P ? "J" : "P";
    return this.tipos[t];
  }
  responder(letra) { this.puntaje[letra]++; this.indice++; }
  reiniciar() { this.puntaje = { E:0, I:0, S:0, N:0, T:0, F:0, J:0, P:0 }; this.indice = 0; }
}
const juego = new JuegoMBTI();
function iniciar() {
  document.getElementById("pantalla-inicio").style.display = "none";
  document.getElementById("pantalla-preguntas").style.display = "block";
  mostrarPregunta();
}
function mostrarPregunta() {
  const p = juego.preguntas[juego.indice];
  const total = juego.preguntas.length;
  document.getElementById("progreso").style.width = (juego.indice / total * 100) + "%";
  document.getElementById("num-pregunta").textContent = `Pregunta ${juego.indice + 1} de ${total}`;
  document.getElementById("texto-pregunta").textContent = p.texto;
  document.getElementById("opciones").innerHTML = `
    <button class="opcion" onclick="responder('${p.letraA}')"><span class="opcion-letra">A</span>${p.opcionA}</button>
    <button class="opcion" onclick="responder('${p.letraB}')"><span class="opcion-letra">B</span>${p.opcionB}</button>
  `;
}
function responder(letra) {
  juego.responder(letra);
  juego.indice < juego.preguntas.length ? mostrarPregunta() : mostrarResultado();
}
function mostrarResultado() {
  document.getElementById("progreso").style.width = "100%";
  const tipo = juego.calcularTipo();
  setTimeout(() => {
    document.getElementById("pantalla-preguntas").style.display = "none";
    document.getElementById("pantalla-resultado").style.display = "block";
    document.getElementById("emoji-resultado").textContent = tipo.emoji;
    document.getElementById("tipo-resultado").textContent = tipo.codigo;
    document.getElementById("nombre-resultado").textContent = tipo.nombre;
    document.getElementById("desc-resultado").textContent = tipo.descripcion;
    document.getElementById("dimensiones-resultado").innerHTML = tipo.dims.map(d =>
      `<div class="dim-card"><div class="dim-letra">${d[0]}</div><div class="dim-nombre">${d}</div></div>`
    ).join("");
  }, 300);
}
function reiniciar() {
  juego.reiniciar();
  document.getElementById("pantalla-resultado").style.display = "none";
  document.getElementById("pantalla-inicio").style.display = "block";
}
</script>
</body>
</html>
"""

display(HTML(HTML_JUEGO))