# -*- coding: utf-8 -*-
"""lagartospock.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KMjEMSHeu4qL2ZTNpnhmSvkVR6LkSySV
"""

import random
import ipywidgets as widgets
from IPython.display import display, clear_output

# ── Datos del juego ──────────────────────────────────────────────────────────
elementos = ['Piedra', 'Papel', 'Tijera', 'Lagarto', 'Spock']
iconos    = ['✊', '✋', '✌️', '🦎', '🖖']

gana = {
    'Piedra':  ['Tijera', 'Lagarto'],
    'Papel':   ['Piedra', 'Spock'],
    'Tijera':  ['Papel',  'Lagarto'],
    'Lagarto': ['Spock',  'Papel'],
    'Spock':   ['Tijera', 'Piedra'],
}

razon = {
    ('Piedra',  'Tijera'):  'La piedra aplasta la tijera',
    ('Piedra',  'Lagarto'): 'La piedra machaca al lagarto',
    ('Papel',   'Piedra'):  'El papel envuelve la piedra',
    ('Papel',   'Spock'):   'El papel desautoriza a Spock',
    ('Tijera',  'Papel'):   'La tijera corta el papel',
    ('Tijera',  'Lagarto'): 'La tijera decapita al lagarto',
    ('Lagarto', 'Spock'):   'El lagarto envenena a Spock',
    ('Lagarto', 'Papel'):   'El lagarto se come el papel',
    ('Spock',   'Tijera'):  'Spock rompe las tijeras',
    ('Spock',   'Piedra'):  'Spock vaporiza la piedra',
}

# ── Estado ───────────────────────────────────────────────────────────────────
estado = {'modo': None, 'turno': 1, 'j1': None, 'v': 0, 'd': 0, 'e': 0}

# ── Widgets ──────────────────────────────────────────────────────────────────
out = widgets.Output()

def hacer_boton(texto, color='#2b2b3b'):
    return widgets.Button(
        description=texto,
        layout=widgets.Layout(width='130px', height='50px', margin='4px'),
        style=widgets.ButtonStyle(button_color=color, font_weight='bold')
    )

def resolver(a, b):
    if a == b:
        return 'empate', '🤝 EMPATE', '#f1c40f', 'Ambos eligieron lo mismo'
    elif b in gana[a]:
        return 'gana_a', '🏆 GANA J1' if estado['modo']=='1v1' else '🏆 GANASTE', '#2ecc71', razon[(a, b)]
    else:
        return 'gana_b', '🏆 GANA J2' if estado['modo']=='1v1' else '💀 PERDISTE', '#e74c3c', razon[(b, a)]

def pantalla_menu():
    with out:
        clear_output(wait=True)
        titulo = widgets.HTML("<h3 style='text-align:center'>✊ Piedra, Papel, Tijera, Lagarto, Spock 🖖</h3>")
        sub    = widgets.HTML("<p style='text-align:center;color:gray'>Selecciona el modo de juego:</p>")
        b1     = hacer_boton('🤖  1 vs Bot', '#1a472a')
        b2     = hacer_boton('👥  1 vs 1',   '#1a3a5c')

        def elegir_bot(_):
            estado.update({'modo': 'bot', 'v': 0, 'd': 0, 'e': 0})
            pantalla_juego()

        def elegir_1v1(_):
            estado.update({'modo': '1v1', 'v': 0, 'd': 0, 'e': 0})
            pantalla_juego()

        b1.on_click(elegir_bot)
        b2.on_click(elegir_1v1)
        display(widgets.VBox([titulo, sub,
            widgets.HBox([b1, b2], layout=widgets.Layout(justify_content='center'))]))

def pantalla_juego():
    with out:
        clear_output(wait=True)
        modo = estado['modo']
        estado['turno'] = 1
        estado['j1'] = None

        if modo == 'bot':
            instruccion = widgets.HTML("<p style='text-align:center'>Elige tu arma 👆</p>")
        else:
            instruccion = widgets.HTML("<p style='text-align:center'><b>Jugador 1</b>, elige tu arma 👆</p>")

        resultado  = widgets.HTML("<div style='height:90px'></div>")
        marcador   = widgets.HTML(f"<p style='text-align:center'>✅ {estado['v']}  ❌ {estado['d']}  🤝 {estado['e']}</p>")

        botones = []
        for i, el in enumerate(elementos):
            b = hacer_boton(f'{iconos[i]}  {el}')
            botones.append(b)

        fila = widgets.HBox(botones, layout=widgets.Layout(justify_content='center', flex_wrap='wrap'))

        btn_menu   = widgets.Button(description='◀ Menú',       layout=widgets.Layout(width='110px', margin='4px'), style=widgets.ButtonStyle(button_color='#333'))
        btn_nuevar = widgets.Button(description='🔄 Nueva ronda', layout=widgets.Layout(width='130px', margin='4px'), style=widgets.ButtonStyle(button_color='#333'))

        def nueva_ronda(_):
            pantalla_juego()

        def ir_menu(_):
            pantalla_menu()

        btn_menu.on_click(ir_menu)
        btn_nuevar.on_click(nueva_ronda)

        def al_click(b):
            eleccion = b.description.split('  ')[1]

            if modo == 'bot':
                maquina = random.choice(elementos)
                ic_j = iconos[elementos.index(eleccion)]
                ic_m = iconos[elementos.index(maquina)]
                _, titulo_r, color, motivo = resolver(eleccion, maquina)
                if 'GANASTE' in titulo_r: estado['v'] += 1
                elif 'PERDISTE' in titulo_r: estado['d'] += 1
                else: estado['e'] += 1
                resultado.value = f"""
                <div style='text-align:center;padding:10px;border:1px solid {color};
                     border-radius:10px;margin:4px 20px'>
                  <div style='font-size:17px;color:{color};font-weight:bold'>{titulo_r}</div>
                  <div style='font-size:22px;margin:6px'>{ic_j} {eleccion} vs {ic_m} {maquina}</div>
                  <div style='color:#aaa;font-size:13px'>{motivo}</div>
                </div>"""
                marcador.value = f"<p style='text-align:center'>✅ {estado['v']}  ❌ {estado['d']}  🤝 {estado['e']}</p>"
                for btn in botones: btn.disabled = False

            else:  # 1 vs 1
                if estado['turno'] == 1:
                    estado['j1'] = eleccion
                    estado['turno'] = 2
                    instruccion.value = "<p style='text-align:center'><b>Jugador 2</b>, elige tu arma 👆</p>"
                    resultado.value = "<p style='text-align:center;color:gray'>J1 ya eligió, turno de J2...</p>"
                    for btn in botones: btn.disabled = False
                else:
                    j1 = estado['j1']
                    j2 = eleccion
                    ic1 = iconos[elementos.index(j1)]
                    ic2 = iconos[elementos.index(j2)]
                    res, titulo_r, color, motivo = resolver(j1, j2)
                    if res == 'gana_a': estado['v'] += 1
                    elif res == 'gana_b': estado['d'] += 1
                    else: estado['e'] += 1
                    resultado.value = f"""
                    <div style='text-align:center;padding:10px;border:1px solid {color};
                         border-radius:10px;margin:4px 20px'>
                      <div style='font-size:17px;color:{color};font-weight:bold'>{titulo_r}</div>
                      <div style='font-size:22px;margin:6px'>J1: {ic1} {j1} vs J2: {ic2} {j2}</div>
                      <div style='color:#aaa;font-size:13px'>{motivo}</div>
                    </div>"""
                    marcador.value = f"<p style='text-align:center'>🥇 J1: {estado['v']}  🥈 J2: {estado['d']}  🤝 {estado['e']}</p>"
                    instruccion.value = "<p style='text-align:center'><b>Jugador 1</b>, elige tu arma 👆</p>"
                    estado['turno'] = 1
                    for btn in botones: btn.disabled = False

        for b in botones:
            b.on_click(al_click)

        barra = widgets.HBox([btn_menu, btn_nuevar], layout=widgets.Layout(justify_content='center'))
        display(widgets.VBox([instruccion, fila, resultado, marcador, barra]))

# ── Arrancar ─────────────────────────────────────────────────────────────────
display(out)
pantalla_menu()