# -*- coding: utf-8 -*-
"""LISTAS2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1k-KXvO6qkNvLXb3DfPNZaRSIrBB_Mpgm

Crea un ejercicio que resuelva una ecuación cuadratica pidiendo los valores de a, b y c
"""

print("ecuacion cuadratica es de la forma ax**2+bx+c")
uno=int(input("Ingrese el valor de a: "))
dos=int(input("Ingrese el valor de b: "))
tres=int(input("Ingrese el valor de c: "))
print("el discriminante es", dos**2 - 4*uno*tres)
print("x1 =", (-dos + (dos**2 - 4*uno*tres)**0.5) / (2*uno))
print("x2 =", (-dos - (dos**2 - 4*uno*tres)**0.5) / (2*uno))

"""ESTRUCTURA WHILE MIENTRAS
No se sabe cuantas veces se debe repetir la acción.

Sintaxis en python

while (condición inicialCI:
  parte del código a repetir
  Modificador de condición inicial CI
CI la CI debe tener un valor de verdad VERDADERO TRUE para  ingresar al while


"""

import random
opciones = {1: "🪨", 2: "🗞️", 3: "✂️"}
yo = int(input("Elige entre 1.🪨, 2.🗞️, 3.✂️: "))
print("Elegiste: {opciones[yo]}")

m=random.randint(1,5)

if me==1:
  print("Empate")
      elif me==1 and l==2:
              print("e maquina eligio 🗞️")
                   elif me==2 and l==3:
                       print(" maquina eligio ✂️")
                          elif me==3 and l==1:
                             print(" máquina eligio 🪨")
                                else: print("Ganaste")

while yo < 1 or yo > 3:
    yo = int(input("Valor no válido. Elige entre 1.🪨, 2.🗞️, 3.✂️: "))

while True:
    entrada = input("Elige entre 1.🪨, 2.📜, 3.✂️: ")
    if entrada in ("1", "2", "3"):
        yo = int(entrada)
        break
    print("Valor no válido. Debe ser 1, 2 o 3.")

print(f"Seleccionaste: {yo}")

import random

opciones = {1:"🪨", 2:"📜", 3:"✂️"}

while True:
    yo = int(input("1.🪨 2.📜 3.✂️: "))
    m = random.randint(1, 3)
    print(f"Tú: {opciones[yo]} | Máquina: {opciones[m]}")

    if yo == m: print("Empate")
    elif (yo==1 and m==3) or (yo==2 and m==1) or (yo==3 and m==2): print("Ganaste!")
    else: print("Perdiste!")

    if input("¿Continuar? si/no: ")  ("si"): break

print("Gracias por jugar.")

a = 0

while input("¿Hay usuario? (si/no): ") == "si":
    while True:
        x = input("¿Qué desea ordenar?: ")
        if x in comida:
            cantidad = int(input(f"¿Cuántas unidades?: "))
            a += precios[comida.index(x)] * cantidad
        else:
            print("Producto no encontrado.")
        if input("¿Algo más? (si/no): ") == "no": break

print(f"Total del día: ${a:,}")

"""FUNCIÓN
Es un pedazo de código que su ejecuta aparte. Aveces se conoce como copiado dinámico.

Ventajas de implementar las funciones

Vuelve el código más limpio
Elimina el código espagueti
Establece un orden de búsqueda

Existen 4 tipos de funciones

Sin parámetro, sin retorno
Sin parámetro, con retorno
Con parámetro, sin retorno
Con parámetro, con retorno
"""

def menu():
    comi = ["Combo 1", "Combo 2", "Combo 3", "Combo 4", "Papas", "Jugos naturales", "Cerveza", "Agua", "Gaseosa"]
    preci = [20000, 25000, 18000, 24500, 3000, 7000, 3500, 4000, 2500]
    for i, (c, p) in enumerate(zip(comi, preci), 1):
        print(f"{i}. {c} - ${p:,}")

menu()

menu()

a = 0

user = input("¿Hay usuario? (s/n): ")
while user == "s":
    r = "s"
    while r == "s":
        menu()
        x = input("¿Qué desea ordenar?: ")
        if x in comida:
            cantidad = int(input("¿Cuántas unidades?: "))
            a = a + precios[comida.index(x)] * cantidad
        else:
            print("Producto no encontrado.")
        r = input("¿Algo más? (s/n): ")
    user = input("¿Hay más usuarios? (s/n): ")

print("Total del día: $" + str(a))

def saludo():
  nombre=input("tu edad es")
  return f"Hola {nombre}. oh que bien"

def saludo():
    nombre = input("¿cuantos años tienes?: ")
    return f"tengo {nombre}, ¡qué bien!"
print(saludo())