# -*- coding: utf-8 -*-
"""QUEST_one.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1glVAUXZ-3ZG7LV0Nw8Q3wf-Yg3Cc5XKD
"""

import ipywidgets as widgets
from IPython.display import display, HTML, clear_output
import re
import random

# ─────────────────────────────────────────────
# ESTADO GLOBAL
# ─────────────────────────────────────────────
G = {
    'xp': 0, 'vidas': 5, 'racha': 0,
    'reto_actual': 0, 'errores': 0,
    'retos_completados': 0, 'combo': 0
}

# ─────────────────────────────────────────────
# INYECTAR ESTILOS PREMIUM
# ─────────────────────────────────────────────
display(HTML("""
<link href="https://fonts.googleapis.com/css2?family=Space+Grotesk:wght@400;600;800&family=JetBrains+Mono:wght@400;600&display=swap" rel="stylesheet">
<style>
  :root {
    --bg:       #06090f;
    --card:     #0d1117;
    --card2:    #111827;
    --border:   #1e2d45;
    --accent:   #00e5ff;
    --purple:   #a259ff;
    --green:    #00ff9d;
    --red:      #ff3c5a;
    --orange:   #ff9500;
    --gold:     #ffd700;
    --text:     #e2e8f0;
    --muted:    #64748b;
    --font:     'Space Grotesk', sans-serif;
    --mono:     'JetBrains Mono', monospace;
  }

  /* ── CONTENEDOR ── */
  .cq-root {
    font-family: var(--font);
    max-width: 820px;
    margin: 0 auto;
    padding: 0 8px;
    background: transparent;
  }

  /* ── INTRO BANNER ── */
  .cq-intro {
    background: linear-gradient(135deg, #0d1117 0%, #111827 100%);
    border: 1px solid var(--border);
    border-top: 3px solid var(--accent);
    border-radius: 16px;
    padding: 32px 36px;
    margin: 12px 0 6px;
    position: relative;
    overflow: hidden;
  }
  .cq-intro::before {
    content: '';
    position: absolute;
    top: -60px; right: -60px;
    width: 200px; height: 200px;
    background: radial-gradient(circle, rgba(0,229,255,.12) 0%, transparent 70%);
    pointer-events: none;
  }
  .cq-intro::after {
    content: '';
    position: absolute;
    bottom: -40px; left: -40px;
    width: 160px; height: 160px;
    background: radial-gradient(circle, rgba(162,89,255,.1) 0%, transparent 70%);
    pointer-events: none;
  }
  .cq-logo {
    font-size: 2.2rem;
    font-weight: 800;
    color: var(--text);
    letter-spacing: -1px;
  }
  .cq-logo span { color: var(--accent); }
  .cq-subtitle {
    color: var(--muted);
    font-size: .88rem;
    margin: 6px 0 20px;
    letter-spacing: .5px;
  }
  .cq-badges {
    display: flex;
    gap: 10px;
    flex-wrap: wrap;
  }
  .cq-badge {
    background: rgba(0,229,255,.06);
    border: 1px solid rgba(0,229,255,.22);
    color: var(--accent);
    border-radius: 100px;
    padding: 5px 14px;
    font-size: .75rem;
    font-weight: 600;
    letter-spacing: .5px;
  }
  .cq-badge.purple {
    background: rgba(162,89,255,.07);
    border-color: rgba(162,89,255,.25);
    color: var(--purple);
  }
  .cq-badge.green {
    background: rgba(0,255,157,.07);
    border-color: rgba(0,255,157,.25);
    color: var(--green);
  }

  /* ── HUD ── */
  .cq-hud {
    background: var(--card);
    border: 1px solid var(--border);
    border-radius: 14px;
    padding: 12px 20px;
    display: flex;
    align-items: center;
    justify-content: space-between;
    margin: 8px 0;
    gap: 10px;
  }
  .cq-hud-left { font-size: .8rem; font-weight: 600; color: var(--muted); letter-spacing: 1px; text-transform: uppercase; }
  .cq-hud-pills { display: flex; gap: 8px; flex-wrap: wrap; }
  .hpill {
    border-radius: 8px;
    padding: 5px 12px;
    font-family: var(--mono);
    font-size: .78rem;
    font-weight: 600;
    display: flex;
    align-items: center;
    gap: 5px;
  }
  .hpill.xp   { background: rgba(255,215,0,.08);  border: 1px solid rgba(255,215,0,.25);  color: var(--gold); }
  .hpill.hp   { background: rgba(255,60,90,.08);   border: 1px solid rgba(255,60,90,.25);  color: var(--red); }
  .hpill.fire { background: rgba(255,149,0,.08);   border: 1px solid rgba(255,149,0,.25);  color: var(--orange); }
  .hpill.prog { background: rgba(0,229,255,.08);   border: 1px solid rgba(0,229,255,.22);  color: var(--accent); }

  /* ── BARRA PROGRESO ── */
  .cq-bar-wrap { margin: 4px 0 12px; }
  .cq-bar-label {
    display: flex; justify-content: space-between;
    font-size: .7rem; color: var(--muted); margin-bottom: 5px; font-weight: 600;
  }
  .cq-bar {
    height: 5px;
    background: rgba(255,255,255,.06);
    border-radius: 100px;
    overflow: hidden;
  }
  .cq-bar-fill {
    height: 100%;
    border-radius: 100px;
    background: linear-gradient(90deg, var(--accent), var(--purple));
    transition: width .4s ease;
  }

  /* ── CONCEPTO ── */
  .cq-concept {
    background: var(--card);
    border: 1px solid var(--border);
    border-left: 3px solid var(--accent);
    border-radius: 0 14px 14px 0;
    padding: 20px 24px;
    margin: 8px 0 4px;
  }
  .cq-concept-tag {
    font-size: .65rem;
    text-transform: uppercase;
    letter-spacing: 3px;
    color: var(--accent);
    margin-bottom: 10px;
    font-weight: 700;
  }
  .cq-concept-title {
    font-size: 1.3rem;
    font-weight: 800;
    color: var(--text);
    margin: 0 0 10px;
  }
  .cq-concept-body {
    color: #94a3b8;
    font-size: .86rem;
    line-height: 1.8;
    margin: 0 0 14px;
  }

  /* ── BLOQUE DE CÓDIGO ── */
  .cq-code {
    background: #0d1117;
    border: 1px solid var(--border);
    border-radius: 10px;
    padding: 16px 20px;
    font-family: var(--mono);
    font-size: .8rem;
    line-height: 2;
    color: var(--text);
    margin: 0 0 6px;
    position: relative;
    overflow-x: auto;
  }
  .cq-code::before {
    content: 'Python';
    position: absolute;
    top: 8px; right: 14px;
    font-size: .6rem;
    color: var(--muted);
    letter-spacing: 2px;
    text-transform: uppercase;
  }
  .kw  { color: #ff7b72; font-weight: 600; }
  .fn  { color: #d2a8ff; }
  .st  { color: #a5d6ff; }
  .nm  { color: #79c0ff; font-weight: 600; }
  .cm  { color: #6e7681; font-style: italic; }
  .vn  { color: #ffa657; }
  .op  { color: #ff7b72; }
  .bl  { color: #e2e8f0; }

  /* ── SEPARADOR ── */
  .cq-divider {
    height: 1px;
    background: linear-gradient(90deg, transparent, var(--border), transparent);
    margin: 18px 0;
  }

  /* ── CARD DE RETO ── */
  .cq-challenge {
    background: var(--card);
    border: 1px solid var(--border);
    border-radius: 14px;
    padding: 20px 24px;
    margin: 8px 0;
    position: relative;
    overflow: hidden;
  }
  .cq-challenge::after {
    content: '';
    position: absolute;
    top: 0; left: 0; right: 0;
    height: 2px;
    background: linear-gradient(90deg, var(--accent), var(--purple));
  }
  .cq-ch-header {
    display: flex;
    align-items: center;
    justify-content: space-between;
    margin-bottom: 14px;
    flex-wrap: wrap;
    gap: 8px;
  }
  .cq-ch-tag {
    font-size: .65rem;
    text-transform: uppercase;
    letter-spacing: 2.5px;
    font-weight: 700;
  }
  .cq-ch-tag.type-mc   { color: var(--accent); }
  .cq-ch-tag.type-fill { color: var(--purple); }
  .cq-ch-tag.type-tf   { color: var(--green); }
  .cq-ch-tag.type-code { color: var(--orange); }
  .cq-xp-badge {
    background: rgba(255,215,0,.1);
    border: 1px solid rgba(255,215,0,.25);
    color: var(--gold);
    border-radius: 6px;
    padding: 2px 10px;
    font-family: var(--mono);
    font-size: .72rem;
    font-weight: 600;
  }
  .cq-question {
    background: rgba(255,255,255,.03);
    border-left: 3px solid rgba(0,229,255,.4);
    border-radius: 0 8px 8px 0;
    padding: 12px 16px;
    font-size: .88rem;
    line-height: 1.8;
    color: #cbd5e1;
    margin-bottom: 16px;
  }

  /* ── OPCIONES ── */
  .cq-options { display: flex; flex-direction: column; gap: 8px; margin-bottom: 14px; }
  .cq-opt {
    background: rgba(255,255,255,.03);
    border: 1px solid var(--border);
    border-radius: 10px;
    padding: 11px 16px;
    cursor: pointer;
    font-size: .86rem;
    color: var(--text);
    transition: all .18s ease;
    display: flex;
    align-items: center;
    gap: 10px;
  }
  .cq-opt:hover { background: rgba(0,229,255,.07); border-color: rgba(0,229,255,.35); transform: translateX(3px); }
  .cq-opt.selected { background: rgba(0,229,255,.1); border-color: rgba(0,229,255,.5); color: var(--accent); }
  .cq-opt.correct  { background: rgba(0,255,157,.1); border-color: rgba(0,255,157,.5); color: var(--green); }
  .cq-opt.wrong    { background: rgba(255,60,90,.1); border-color: rgba(255,60,90,.4); color: var(--red); }
  .cq-opt.disabled { pointer-events: none; opacity: .65; }
  .cq-opt-letter {
    width: 26px; height: 26px;
    border-radius: 6px;
    background: rgba(255,255,255,.06);
    display: flex; align-items: center; justify-content: center;
    font-size: .75rem;
    font-weight: 700;
    font-family: var(--mono);
    flex-shrink: 0;
  }

  /* ── INPUT TEXTO ── */
  .cq-input-wrap { margin-bottom: 14px; }
  .cq-input {
    width: 100%;
    max-width: 340px;
    background: rgba(255,255,255,.04);
    border: 1px solid var(--border);
    border-radius: 10px;
    padding: 10px 16px;
    font-family: var(--mono);
    font-size: .88rem;
    color: var(--text);
    outline: none;
    transition: border-color .2s;
    box-sizing: border-box;
  }
  .cq-input:focus { border-color: var(--accent); }

  /* ── BOTONES ── */
  .cq-btn-row { display: flex; gap: 10px; flex-wrap: wrap; margin-bottom: 10px; }
  .cq-btn {
    border: none;
    border-radius: 10px;
    padding: 9px 20px;
    font-family: var(--font);
    font-size: .84rem;
    font-weight: 700;
    cursor: pointer;
    transition: all .18s ease;
    letter-spacing: .3px;
  }
  .cq-btn:hover { transform: translateY(-1px); filter: brightness(1.1); }
  .cq-btn:active { transform: translateY(0); }
  .cq-btn.primary { background: var(--accent); color: #000; }
  .cq-btn.danger  { background: var(--red);    color: #fff; }
  .cq-btn.success { background: var(--green);  color: #000; }
  .cq-btn.hint    { background: rgba(162,89,255,.15); border: 1px solid rgba(162,89,255,.35); color: var(--purple); }
  .cq-btn.tf-v    { background: rgba(0,255,157,.15);  border: 1px solid rgba(0,255,157,.4);  color: var(--green); font-size: .9rem; padding: 11px 28px; }
  .cq-btn.tf-f    { background: rgba(255,60,90,.12);  border: 1px solid rgba(255,60,90,.4);  color: var(--red);   font-size: .9rem; padding: 11px 28px; }

  /* ── FEEDBACK ── */
  .cq-ok, .cq-err, .cq-hint {
    border-radius: 10px;
    padding: 11px 16px;
    font-size: .86rem;
    line-height: 1.6;
    margin-top: 6px;
    display: flex;
    gap: 10px;
    align-items: flex-start;
  }
  .cq-ok   { background: rgba(0,255,157,.08);  border: 1px solid rgba(0,255,157,.3);  color: #7affcc; }
  .cq-err  { background: rgba(255,60,90,.08);   border: 1px solid rgba(255,60,90,.3);  color: #ff8095; }
  .cq-hint { background: rgba(162,89,255,.08); border: 1px solid rgba(162,89,255,.3); color: #c4a8ff; }
  .cq-icon { font-size: 1.1rem; flex-shrink: 0; margin-top: 1px; }

  /* ── COMBO BANNER ── */
  .cq-combo {
    background: linear-gradient(135deg, rgba(255,215,0,.12), rgba(255,149,0,.08));
    border: 1px solid rgba(255,215,0,.3);
    border-radius: 10px;
    padding: 10px 16px;
    font-size: .84rem;
    color: var(--gold);
    font-weight: 700;
    margin-top: 8px;
    text-align: center;
    animation: pulse 1.2s ease-in-out;
  }
  @keyframes pulse {
    0%   { transform: scale(.97); opacity: .7; }
    50%  { transform: scale(1.01); opacity: 1; }
    100% { transform: scale(1); opacity: 1; }
  }

  /* ── PANTALLA VICTORIA ── */
  .cq-win {
    background: linear-gradient(135deg, #0d1117 0%, #111827 100%);
    border: 2px solid var(--gold);
    border-radius: 18px;
    padding: 40px 32px;
    text-align: center;
    position: relative;
    overflow: hidden;
    margin: 12px 0;
  }
  .cq-win::before {
    content: '';
    position: absolute;
    top: 50%; left: 50%;
    transform: translate(-50%, -50%);
    width: 300px; height: 300px;
    background: radial-gradient(circle, rgba(255,215,0,.06) 0%, transparent 70%);
    pointer-events: none;
  }
  .cq-win h1 {
    color: var(--gold);
    font-size: 2rem;
    font-weight: 800;
    margin: 10px 0 6px;
    letter-spacing: -1px;
  }
  .cq-win-sub { color: var(--muted); font-size: .9rem; margin-bottom: 24px; }
  .cq-stats {
    display: flex;
    gap: 12px;
    justify-content: center;
    flex-wrap: wrap;
    margin: 20px 0;
  }
  .cq-stat {
    background: rgba(255,255,255,.04);
    border: 1px solid var(--border);
    border-radius: 12px;
    padding: 16px 24px;
    min-width: 90px;
  }
  .cq-sv {
    font-family: var(--mono);
    font-size: 1.8rem;
    color: var(--gold);
    font-weight: 700;
  }
  .cq-sl { font-size: .7rem; color: var(--muted); margin-top: 4px; text-transform: uppercase; letter-spacing: 1px; }

  /* ── INLINE CODE ── */
  code {
    background: rgba(0,229,255,.1);
    color: var(--accent);
    padding: 1px 6px;
    border-radius: 5px;
    font-family: var(--mono);
    font-size: .85em;
  }

  /* ── TEXTAREA ── */
  .cq-textarea {
    width: 100%;
    max-width: 480px;
    background: rgba(255,255,255,.03);
    border: 1px solid var(--border);
    border-radius: 10px;
    padding: 12px 16px;
    font-family: var(--mono);
    font-size: .82rem;
    color: var(--text);
    resize: vertical;
    min-height: 70px;
    box-sizing: border-box;
    outline: none;
    line-height: 1.7;
  }
  .cq-textarea:focus { border-color: var(--purple); }

  /* Ocultar widgets de ipython por defecto */
  .widget-radio-box { color: var(--text) !important; }
</style>
"""))

# ─────────────────────────────────────────────
# HELPERS
# ─────────────────────────────────────────────
TOTAL_RETOS = 10

def hud_html():
    hp_icons = '❤️' * G['vidas'] + '🖤' * (5 - G['vidas'])
    pct = int(G['retos_completados'] / TOTAL_RETOS * 100)
    combo_txt = f"🔥 ×{G['racha']}" if G['racha'] >= 2 else f"🔥 {G['racha']}"
    return f"""
<div class="cq-root">
  <div class="cq-hud">
    <div class="cq-hud-left">Python · Nivel 1</div>
    <div class="cq-hud-pills">
      <span class="hpill xp">⚡ {G['xp']} XP</span>
      <span class="hpill hp">{hp_icons}</span>
      <span class="hpill fire">{combo_txt}</span>
      <span class="hpill prog">Reto {G['reto_actual']}/{TOTAL_RETOS}</span>
    </div>
  </div>
  <div class="cq-bar-wrap">
    <div class="cq-bar-label">
      <span>Progreso</span>
      <span>{pct}%</span>
    </div>
    <div class="cq-bar"><div class="cq-bar-fill" style="width:{pct}%"></div></div>
  </div>
</div>"""

def ganar_xp(n, combo_bonus=True):
    bonus = 0
    if combo_bonus and G['racha'] >= 3:
        bonus = int(n * 0.5)
    G['xp'] += n + bonus
    G['racha'] += 1
    G['combo'] = G['racha']
    G['retos_completados'] += 1
    return bonus

def perder_vida():
    G['vidas'] = max(0, G['vidas'] - 1)
    G['racha'] = 0
    G['errores'] += 1

def combo_html(bonus):
    if bonus > 0:
        return f'<div class="cq-combo">🔥 ¡COMBO ×{G["racha"]-1}! +{bonus} XP extra</div>'
    return ''

def ok_html(msg, bonus=0):
    cb = combo_html(bonus)
    return f'<div class="cq-ok"><span class="cq-icon">✅</span><div>{msg}</div></div>{cb}'

def err_html(msg):
    vidas = G['vidas']
    alerta = '' if vidas > 1 else ' <strong>¡Última vida!</strong>'
    return f'<div class="cq-err"><span class="cq-icon">❌</span><div>{msg}{alerta}</div></div>'

def hint_html(msg):
    return f'<div class="cq-hint"><span class="cq-icon">💡</span><div>{msg}</div></div>'

def reto_header(numero, tipo_label, tipo_class, xp_val, pregunta):
    return f"""
<div class="cq-root">
  <div class="cq-challenge">
    <div class="cq-ch-header">
      <span class="cq-ch-tag {tipo_class}">Reto {numero} · {tipo_label}</span>
      <span class="cq-xp-badge">+{xp_val} XP</span>
    </div>
    <div class="cq-question">{pregunta}</div>
  </div>
</div>"""

# ─────────────────────────────────────────────
# PANTALLA INTRO
# ─────────────────────────────────────────────
display(HTML(f"""
<div class="cq-root">
  <div class="cq-intro">
    <div class="cq-logo">Code<span>Quest</span></div>
    <div class="cq-subtitle">🐍 Python · Nivel 1 — Variables &amp; Tipos de Datos</div>
    <div class="cq-badges">
      <span class="cq-badge">10 Retos</span>
      <span class="cq-badge purple">5 Vidas</span>
      <span class="cq-badge green">Combos XP</span>
      <span class="cq-badge">Sistema Antitrampas</span>
    </div>
  </div>
</div>"""))

# ─────────────────────────────────────────────
# CONCEPTO
# ─────────────────────────────────────────────
display(HTML(f"""
{hud_html()}
<div class="cq-root">
  <div class="cq-concept">
    <div class="cq-concept-tag">📖 Conceptos Clave — Antes de empezar</div>
    <div class="cq-concept-title">Variables &amp; Tipos de Datos en Python</div>
    <p class="cq-concept-body">
      Una <strong>variable</strong> es un nombre que apunta a un valor en memoria.
      Se crea con <code>=</code>. Python infiere el <strong>tipo</strong> automáticamente.
      Los cuatro tipos básicos son: <code>str</code>, <code>int</code>, <code>float</code> y <code>bool</code>.
    </p>
    <div class="cq-code">
<span class="vn">nombre</span> <span class="op">=</span> <span class="st">"Ana"</span>        <span class="cm"># str   → texto (cadena)</span>
<span class="vn">edad</span>   <span class="op">=</span> <span class="nm">20</span>          <span class="cm"># int   → número entero</span>
<span class="vn">nota</span>   <span class="op">=</span> <span class="nm">9.5</span>         <span class="cm"># float → número decimal</span>
<span class="vn">activo</span> <span class="op">=</span> <span class="kw">True</span>        <span class="cm"># bool  → True / False</span>
<br>
<span class="fn">print</span>(<span class="fn">type</span>(<span class="vn">nombre</span>))   <span class="cm"># → &lt;class 'str'&gt;</span>
<span class="fn">print</span>(<span class="fn">type</span>(<span class="vn">edad</span>))     <span class="cm"># → &lt;class 'int'&gt;</span>
<span class="fn">print</span>(<span class="vn">nombre</span>, <span class="vn">edad</span>)  <span class="cm"># → Ana 20</span>
    </div>
  </div>
</div>"""))

G['reto_actual'] = 1

# ══════════════════════════════════════════════════════════════
# RETO 1 — Opción múltiple básica
# ══════════════════════════════════════════════════════════════
display(HTML('<div class="cq-root"><div class="cq-divider"></div></div>'))
display(HTML(reto_header(1, "Selección múltiple", "type-mc", 25,
    '¿Cuál línea guarda correctamente <code>"Python"</code> en la variable <code>lenguaje</code>?')))

OPC1 = [
    ('A', 'lenguaje == "Python"'),
    ('B', 'lenguaje = "Python"'),
    ('C', '"Python" = lenguaje'),
    ('D', 'var lenguaje = "Python"'),
]

sel1 = {'v': None}
out1 = widgets.Output()
btns1_verify = widgets.Button(description='✔  Verificar', layout=widgets.Layout(width='150px', height='38px'))
btns1_hint   = widgets.Button(description='💡 Pista -5XP', layout=widgets.Layout(width='140px', height='38px'))
btns1_verify.add_class('cq-btn'); btns1_hint.add_class('cq-btn')

opt_buttons1 = []
for letra, txt in OPC1:
    b = widgets.Button(
        description=f'{letra})  {txt}',
        layout=widgets.Layout(width='100%', height='44px')
    )
    b.style.button_color = '#111827'
    b.style.text_color   = '#e2e8f0'
    opt_buttons1.append(b)

def make_sel1(letra, btn):
    def handler(b):
        sel1['v'] = letra
        for ob in opt_buttons1:
            ob.style.button_color = '#111827'
            ob.style.text_color   = '#e2e8f0'
        btn.style.button_color = '#0d2d3d'
        btn.style.text_color   = '#00e5ff'
    return handler

for letra_txt, btn in zip([l for l,_ in OPC1], opt_buttons1):
    btn.on_click(make_sel1(letra_txt, btn))

def click_v1(b):
    with out1:
        clear_output(wait=True)
        if sel1['v'] is None:
            display(HTML(hint_html('Selecciona una opción primero.')))
            return
        if sel1['v'] == 'B':
            bonus = ganar_xp(25)
            for ob in opt_buttons1: ob.disabled = True
            btns1_verify.disabled = True
            display(HTML(ok_html('En Python <code>=</code> asigna valores. La variable va siempre a la <strong>izquierda</strong>.', bonus)))
        else:
            perder_vida()
            display(HTML(err_html('Recuerda: <code>variable = valor</code>. El <code>==</code> compara, no asigna.')))

def click_h1(b):
    with out1:
        clear_output(wait=True)
        G['xp'] = max(0, G['xp'] - 5)
        display(HTML(hint_html('La variable va a la <strong>izquierda</strong> del <code>=</code>.')))

btns1_verify.on_click(click_v1)
btns1_hint.on_click(click_h1)
for btn in opt_buttons1:
    display(btn)
display(widgets.HBox([btns1_verify, btns1_hint]))
display(out1)

# ══════════════════════════════════════════════════════════════
# RETO 2 — Opción múltiple: tipos
# ══════════════════════════════════════════════════════════════
G['reto_actual'] = 2
display(HTML('<div class="cq-root"><div class="cq-divider"></div></div>'))
display(HTML(reto_header(2, "Selección múltiple", "type-mc", 25,
    '¿Qué tipo de dato es <code>3.14</code>?')))

OPC2 = [('A','int'), ('B','str'), ('C','float'), ('D','bool')]
sel2 = {'v': None}
out2 = widgets.Output()
btn2_v = widgets.Button(description='✔  Verificar', layout=widgets.Layout(width='150px', height='38px'))
btn2_h = widgets.Button(description='💡 Pista -5XP', layout=widgets.Layout(width='140px', height='38px'))
opt_buttons2 = []
for letra, txt in OPC2:
    b = widgets.Button(description=f'{letra})  {txt}', layout=widgets.Layout(width='100%', height='44px'))
    b.style.button_color = '#111827'; b.style.text_color = '#e2e8f0'
    opt_buttons2.append(b)

def make_sel2(letra, btn):
    def h(b):
        sel2['v'] = letra
        for ob in opt_buttons2: ob.style.button_color = '#111827'; ob.style.text_color = '#e2e8f0'
        btn.style.button_color = '#1a1040'; btn.style.text_color = '#a259ff'
    return h

for (l,_), btn in zip(OPC2, opt_buttons2):
    btn.on_click(make_sel2(l, btn))

def click_v2(b):
    with out2:
        clear_output(wait=True)
        if sel2['v'] is None:
            display(HTML(hint_html('Selecciona una opción primero.'))); return
        if sel2['v'] == 'C':
            bonus = ganar_xp(25)
            for ob in opt_buttons2: ob.disabled = True
            btn2_v.disabled = True
            display(HTML(ok_html('<code>3.14</code> tiene punto decimal → es <code>float</code>. Sin punto sería <code>int</code>.', bonus)))
        else:
            perder_vida()
            display(HTML(err_html('¿Tiene punto decimal? Entonces es <code>float</code>.')))

def click_h2(b):
    with out2:
        clear_output(wait=True)
        G['xp'] = max(0, G['xp'] - 5)
        display(HTML(hint_html('Los números con punto decimal son de tipo <code>float</code>.')))

btn2_v.on_click(click_v2); btn2_h.on_click(click_h2)
for btn in opt_buttons2: display(btn)
display(widgets.HBox([btn2_v, btn2_h])); display(out2)

# ══════════════════════════════════════════════════════════════
# RETO 3 — Opción múltiple: print
# ══════════════════════════════════════════════════════════════
G['reto_actual'] = 3
display(HTML('<div class="cq-root"><div class="cq-divider"></div></div>'))
display(HTML(reto_header(3, "Selección múltiple", "type-mc", 30,
    'Dado este código:<br><br><code>x = 5</code><br><code>y = 2</code><br><code>print(x + y)</code><br><br>¿Qué imprime?')))

OPC3 = [('A','52'), ('B','x + y'), ('C','7'), ('D','Error')]
sel3 = {'v': None}
out3 = widgets.Output()
btn3_v = widgets.Button(description='✔  Verificar', layout=widgets.Layout(width='150px', height='38px'))
btn3_h = widgets.Button(description='💡 Pista -5XP', layout=widgets.Layout(width='140px', height='38px'))
opt_buttons3 = []
for letra, txt in OPC3:
    b = widgets.Button(description=f'{letra})  {txt}', layout=widgets.Layout(width='100%', height='44px'))
    b.style.button_color = '#111827'; b.style.text_color = '#e2e8f0'
    opt_buttons3.append(b)

def make_sel3(letra, btn):
    def h(b):
        sel3['v'] = letra
        for ob in opt_buttons3: ob.style.button_color = '#111827'; ob.style.text_color = '#e2e8f0'
        btn.style.button_color = '#0a1a25'; btn.style.text_color = '#00e5ff'
    return h

for (l,_), btn in zip(OPC3, opt_buttons3): btn.on_click(make_sel3(l, btn))

def click_v3(b):
    with out3:
        clear_output(wait=True)
        if sel3['v'] is None:
            display(HTML(hint_html('Selecciona una opción primero.'))); return
        if sel3['v'] == 'C':
            bonus = ganar_xp(30)
            for ob in opt_buttons3: ob.disabled = True
            btn3_v.disabled = True
            display(HTML(ok_html('<code>x + y</code> → <code>5 + 2</code> → <code>7</code>. Python evalúa la expresión y muestra el resultado.', bonus)))
        else:
            perder_vida()
            display(HTML(err_html('<code>x</code> vale <code>5</code> y <code>y</code> vale <code>2</code>. Súmalos.')))

def click_h3(b):
    with out3:
        clear_output(wait=True)
        G['xp'] = max(0, G['xp'] - 5)
        display(HTML(hint_html('Sustituye las variables: <code>x = 5</code>, <code>y = 2</code>. ¿Cuánto es 5 + 2?')))

btn3_v.on_click(click_v3); btn3_h.on_click(click_h3)
for btn in opt_buttons3: display(btn)
display(widgets.HBox([btn3_v, btn3_h])); display(out3)

# ══════════════════════════════════════════════════════════════
# RETO 4 — Opción múltiple: bool
# ══════════════════════════════════════════════════════════════
G['reto_actual'] = 4
display(HTML('<div class="cq-root"><div class="cq-divider"></div></div>'))
display(HTML(reto_header(4, "Selección múltiple", "type-mc", 25,
    '¿Cuáles de los siguientes son valores <code>bool</code> válidos en Python?')))

OPC4 = [
    ('A', 'true  y  false'),
    ('B', 'True  y  False'),
    ('C', '"True"  y  "False"'),
    ('D', '1  y  0  únicamente'),
]
sel4 = {'v': None}
out4 = widgets.Output()
btn4_v = widgets.Button(description='✔  Verificar', layout=widgets.Layout(width='150px', height='38px'))
btn4_h = widgets.Button(description='💡 Pista -5XP', layout=widgets.Layout(width='140px', height='38px'))
opt_buttons4 = []
for letra, txt in OPC4:
    b = widgets.Button(description=f'{letra})  {txt}', layout=widgets.Layout(width='100%', height='44px'))
    b.style.button_color = '#111827'; b.style.text_color = '#e2e8f0'
    opt_buttons4.append(b)

def make_sel4(letra, btn):
    def h(b):
        sel4['v'] = letra
        for ob in opt_buttons4: ob.style.button_color = '#111827'; ob.style.text_color = '#e2e8f0'
        btn.style.button_color = '#1a1040'; btn.style.text_color = '#a259ff'
    return h

for (l,_), btn in zip(OPC4, opt_buttons4): btn.on_click(make_sel4(l, btn))

def click_v4(b):
    with out4:
        clear_output(wait=True)
        if sel4['v'] is None:
            display(HTML(hint_html('Selecciona una opción primero.'))); return
        if sel4['v'] == 'B':
            bonus = ganar_xp(25)
            for ob in opt_buttons4: ob.disabled = True
            btn4_v.disabled = True
            display(HTML(ok_html('Python distingue mayúsculas: <code>True</code> y <code>False</code> con inicial mayúscula. <code>true</code> en minúsculas daría error.', bonus)))
        else:
            perder_vida()
            display(HTML(err_html('Python es <em>case-sensitive</em>. Los booleanos se escriben con la <strong>primera letra en mayúscula</strong>.')))

def click_h4(b):
    with out4:
        clear_output(wait=True)
        G['xp'] = max(0, G['xp'] - 5)
        display(HTML(hint_html('Python diferencia mayúsculas. La respuesta correcta empieza con mayúscula.')))

btn4_v.on_click(click_v4); btn4_h.on_click(click_h4)
for btn in opt_buttons4: display(btn)
display(widgets.HBox([btn4_v, btn4_h])); display(out4)

# ══════════════════════════════════════════════════════════════
# RETO 5 — Completar código
# ══════════════════════════════════════════════════════════════
G['reto_actual'] = 5
display(HTML('<div class="cq-root"><div class="cq-divider"></div></div>'))
display(HTML(reto_header(5, "Completar código", "type-fill", 30,
    '¿Qué valor va en el espacio para que <code>temperatura</code> guarde el número <strong>36.6</strong>?<br><br><code>temperatura = ___</code>')))

txt5 = widgets.Text(placeholder='Escribe aquí...', layout=widgets.Layout(width='220px'))
btn5_v = widgets.Button(description='✔  Verificar', layout=widgets.Layout(width='150px', height='38px'))
btn5_h = widgets.Button(description='💡 Pista -5XP', layout=widgets.Layout(width='140px', height='38px'))
out5 = widgets.Output()

def click_v5(b):
    with out5:
        clear_output(wait=True)
        r = txt5.value.strip()
        if r == '36.6':
            bonus = ganar_xp(30)
            txt5.disabled = True; btn5_v.disabled = True
            display(HTML(ok_html('<code>temperatura = 36.6</code> — sin comillas porque es un número decimal <code>float</code>.', bonus)))
        else:
            perder_vida()
            display(HTML(err_html(f'<code>temperatura = {r or "?"}</code> no es correcto. Escribe el número tal cual, sin comillas.')))

def click_h5(b):
    with out5:
        clear_output(wait=True)
        G['xp'] = max(0, G['xp'] - 5)
        display(HTML(hint_html('Un número decimal en Python se escribe con punto: <code>36.6</code>')))

btn5_v.on_click(click_v5); btn5_h.on_click(click_h5)
display(txt5)
display(widgets.HBox([btn5_v, btn5_h])); display(out5)

# ══════════════════════════════════════════════════════════════
# RETO 6 — Verdadero / Falso
# ══════════════════════════════════════════════════════════════
G['reto_actual'] = 6
display(HTML('<div class="cq-root"><div class="cq-divider"></div></div>'))
display(HTML(reto_header(6, "Verdadero o Falso", "type-tf", 20,
    '<em>"En Python puedes cambiar el valor de una variable en cualquier momento simplemente asignándole un nuevo valor."</em>')))

out6 = widgets.Output()
btnV6 = widgets.Button(description='✅  Verdadero', layout=widgets.Layout(width='160px', height='44px'))
btnF6 = widgets.Button(description='❌  Falso',     layout=widgets.Layout(width='160px', height='44px'))
btnV6.style.button_color = '#0a2218'; btnV6.style.text_color = '#00ff9d'
btnF6.style.button_color = '#220a10'; btnF6.style.text_color = '#ff3c5a'

def click_V6(b):
    with out6:
        clear_output(wait=True)
        btnV6.disabled = True; btnF6.disabled = True
        bonus = ganar_xp(20)
        display(HTML(ok_html('¡Correcto! Python es dinámico: <code>x = 5</code> y luego <code>x = "hola"</code> es perfectamente válido.', bonus)))

def click_F6(b):
    with out6:
        clear_output(wait=True)
        btnV6.disabled = True; btnF6.disabled = True
        perder_vida()
        display(HTML(err_html('Es <strong>Verdadero</strong>. Python permite reasignar variables con un nuevo valor en cualquier momento.')))

btnV6.on_click(click_V6); btnF6.on_click(click_F6)
display(widgets.HBox([btnV6, btnF6])); display(out6)

# ══════════════════════════════════════════════════════════════
# RETO 7 — Opción múltiple: concatenación
# ══════════════════════════════════════════════════════════════
G['reto_actual'] = 7
display(HTML('<div class="cq-root"><div class="cq-divider"></div></div>'))
display(HTML(reto_header(7, "Selección múltiple", "type-mc", 35,
    '¿Qué imprime este código?<br><br>'
    '<code>a = "Hola"</code><br><code>b = " Mundo"</code><br><code>print(a + b)</code>')))

OPC7 = [('A','Hola'), ('B','Hola Mundo'), ('C','a + b'), ('D','Error: no se puede sumar str')]
sel7 = {'v': None}
out7 = widgets.Output()
btn7_v = widgets.Button(description='✔  Verificar', layout=widgets.Layout(width='150px', height='38px'))
btn7_h = widgets.Button(description='💡 Pista -5XP', layout=widgets.Layout(width='140px', height='38px'))
opt_buttons7 = []
for letra, txt in OPC7:
    b = widgets.Button(description=f'{letra})  {txt}', layout=widgets.Layout(width='100%', height='44px'))
    b.style.button_color = '#111827'; b.style.text_color = '#e2e8f0'
    opt_buttons7.append(b)

def make_sel7(letra, btn):
    def h(b):
        sel7['v'] = letra
        for ob in opt_buttons7: ob.style.button_color = '#111827'; ob.style.text_color = '#e2e8f0'
        btn.style.button_color = '#0a1a25'; btn.style.text_color = '#00e5ff'
    return h

for (l,_), btn in zip(OPC7, opt_buttons7): btn.on_click(make_sel7(l, btn))

def click_v7(b):
    with out7:
        clear_output(wait=True)
        if sel7['v'] is None:
            display(HTML(hint_html('Selecciona una opción primero.'))); return
        if sel7['v'] == 'B':
            bonus = ganar_xp(35)
            for ob in opt_buttons7: ob.disabled = True
            btn7_v.disabled = True
            display(HTML(ok_html('El operador <code>+</code> sobre strings los <strong>concatena</strong> (une). <code>"Hola" + " Mundo"</code> → <code>"Hola Mundo"</code>.', bonus)))
        else:
            perder_vida()
            display(HTML(err_html('En Python <code>+</code> con strings los une. <code>"Hola" + " Mundo"</code> → <code>"Hola Mundo"</code>')))

def click_h7(b):
    with out7:
        clear_output(wait=True)
        G['xp'] = max(0, G['xp'] - 5)
        display(HTML(hint_html('<code>+</code> entre textos los <strong>concatena</strong>. Nota el espacio al inicio de <code>" Mundo"</code>.')))

btn7_v.on_click(click_v7); btn7_h.on_click(click_h7)
for btn in opt_buttons7: display(btn)
display(widgets.HBox([btn7_v, btn7_h])); display(out7)

# ══════════════════════════════════════════════════════════════
# RETO 8 — Opción múltiple: nombres de variables
# ══════════════════════════════════════════════════════════════
G['reto_actual'] = 8
display(HTML('<div class="cq-root"><div class="cq-divider"></div></div>'))
display(HTML(reto_header(8, "Selección múltiple", "type-mc", 30,
    '¿Cuál de estos nombres de variable es <strong>inválido</strong> en Python?')))

OPC8 = [
    ('A', '_mi_var'),
    ('B', 'miVar2'),
    ('C', '2miVar'),
    ('D', 'mi_variable_larga'),
]
sel8 = {'v': None}
out8 = widgets.Output()
btn8_v = widgets.Button(description='✔  Verificar', layout=widgets.Layout(width='150px', height='38px'))
btn8_h = widgets.Button(description='💡 Pista -5XP', layout=widgets.Layout(width='140px', height='38px'))
opt_buttons8 = []
for letra, txt in OPC8:
    b = widgets.Button(description=f'{letra})  {txt}', layout=widgets.Layout(width='100%', height='44px'))
    b.style.button_color = '#111827'; b.style.text_color = '#e2e8f0'
    opt_buttons8.append(b)

def make_sel8(letra, btn):
    def h(b):
        sel8['v'] = letra
        for ob in opt_buttons8: ob.style.button_color = '#111827'; ob.style.text_color = '#e2e8f0'
        btn.style.button_color = '#1a1040'; btn.style.text_color = '#a259ff'
    return h

for (l,_), btn in zip(OPC8, opt_buttons8): btn.on_click(make_sel8(l, btn))

def click_v8(b):
    with out8:
        clear_output(wait=True)
        if sel8['v'] is None:
            display(HTML(hint_html('Selecciona una opción primero.'))); return
        if sel8['v'] == 'C':
            bonus = ganar_xp(30)
            for ob in opt_buttons8: ob.disabled = True
            btn8_v.disabled = True
            display(HTML(ok_html('<code>2miVar</code> empieza con número → <strong>inválido</strong>. Los nombres deben iniciar con letra o guion bajo <code>_</code>.', bonus)))
        else:
            perder_vida()
            display(HTML(err_html('Las variables no pueden <strong>empezar con número</strong>. Busca cuál opción empieza con dígito.')))

def click_h8(b):
    with out8:
        clear_output(wait=True)
        G['xp'] = max(0, G['xp'] - 5)
        display(HTML(hint_html('Las variables deben comenzar con <strong>letra</strong> o <code>_</code>, nunca con un número.')))

btn8_v.on_click(click_v8); btn8_h.on_click(click_h8)
for btn in opt_buttons8: display(btn)
display(widgets.HBox([btn8_v, btn8_h])); display(out8)

# ══════════════════════════════════════════════════════════════
# RETO 9 — Verdadero / Falso
# ══════════════════════════════════════════════════════════════
G['reto_actual'] = 9
display(HTML('<div class="cq-root"><div class="cq-divider"></div></div>'))
display(HTML(reto_header(9, "Verdadero o Falso", "type-tf", 20,
    '<em>"<code>len("Python")</code> retorna el valor <code>7</code>."</em>')))

out9 = widgets.Output()
btnV9 = widgets.Button(description='✅  Verdadero', layout=widgets.Layout(width='160px', height='44px'))
btnF9 = widgets.Button(description='❌  Falso',     layout=widgets.Layout(width='160px', height='44px'))
btnV9.style.button_color = '#0a2218'; btnV9.style.text_color = '#00ff9d'
btnF9.style.button_color = '#220a10'; btnF9.style.text_color = '#ff3c5a'

def click_V9(b):
    with out9:
        clear_output(wait=True)
        btnV9.disabled = True; btnF9.disabled = True
        perder_vida()
        display(HTML(err_html('Es <strong>Falso</strong>. <code>"Python"</code> tiene <code>6</code> letras, no 7. <code>len()</code> cuenta caracteres exactamente.')))

def click_F9(b):
    with out9:
        clear_output(wait=True)
        btnV9.disabled = True; btnF9.disabled = True
        bonus = ganar_xp(20)
        display(HTML(ok_html('¡Correcto! <code>"Python"</code> tiene 6 letras → <code>len("Python")</code> devuelve <code>6</code>.', bonus)))

btnV9.on_click(click_V9); btnF9.on_click(click_F9)
display(widgets.HBox([btnV9, btnF9])); display(out9)

# ══════════════════════════════════════════════════════════════
# RETO 10 — Reto final: escribir código
# ══════════════════════════════════════════════════════════════
G['reto_actual'] = 10
display(HTML('<div class="cq-root"><div class="cq-divider"></div></div>'))
display(HTML(reto_header(10, "🔥 Reto Final — Escribir código", "type-code", 50,
    'Escribe <strong>una línea</strong> que cree la variable <code>pais</code> con el valor <code>"Colombia"</code>.')))

area10 = widgets.Textarea(
    placeholder='# Escribe aquí tu línea de código...',
    layout=widgets.Layout(width='440px', height='70px')
)
btn10_v = widgets.Button(description='▶  Ejecutar', layout=widgets.Layout(width='140px', height='38px'))
btn10_h = widgets.Button(description='💡 Pista -5XP', layout=widgets.Layout(width='140px', height='38px'))
out10 = widgets.Output()

def click_v10(b):
    with out10:
        clear_output(wait=True)
        cod = area10.value.strip()
        if re.match(r'^pais\s*=\s*["\']Colombia["\']$', cod):
            bonus = ganar_xp(50)
            btn10_v.disabled = True
            display(HTML(ok_html(f'<code>{cod}</code> — ¡Perfecto! Variable creada con texto entre comillas.', bonus)))
            # ─── PANTALLA VICTORIA ───
            total_xp = G['xp']
            vidas    = G['vidas']
            errores  = G['errores']
            pct      = max(0, int((TOTAL_RETOS - errores) / TOTAL_RETOS * 100))
            stars    = '⭐' * (3 if errores == 0 else 2 if errores <= 2 else 1)
            grade    = 'S+' if errores == 0 else 'A' if errores <= 2 else 'B' if errores <= 4 else 'C'
            grade_color = '#ffd700' if errores == 0 else '#00ff9d' if errores <= 2 else '#a259ff' if errores <= 4 else '#ff9500'
            display(HTML(f"""
<div class="cq-root">
  <div style="margin:16px 0"></div>
  <div class="cq-win">
    <div style="font-size:3.2rem;margin-bottom:4px">🎉</div>
    <div style="font-size:1.6rem;letter-spacing:2px;margin:6px 0">{stars}</div>
    <h1>¡Nivel 1 Completado!</h1>
    <p class="cq-win-sub">¡Dominaste Variables &amp; Tipos de Datos en Python!</p>
    <div class="cq-stats">
      <div class="cq-stat">
        <div class="cq-sv">{total_xp}</div>
        <div class="cq-sl">XP Ganados</div>
      </div>
      <div class="cq-stat">
        <div class="cq-sv" style="color:{grade_color}">{grade}</div>
        <div class="cq-sl">Calificación</div>
      </div>
      <div class="cq-stat">
        <div class="cq-sv">{pct}%</div>
        <div class="cq-sl">Precisión</div>
      </div>
      <div class="cq-stat">
        <div class="cq-sv">{vidas}/5</div>
        <div class="cq-sl">Vidas finales</div>
      </div>
      <div class="cq-stat">
        <div class="cq-sv">{G['combo']}</div>
        <div class="cq-sl">Combo máx.</div>
      </div>
    </div>
    <div style="background:rgba(255,255,255,.03);border:1px solid #1e2d45;border-radius:10px;
                padding:14px 20px;font-size:.82rem;color:#64748b;margin-top:8px">
      🐍 Siguiente: <strong style="color:#00e5ff">Nivel 2 — Condicionales &amp; Bucles</strong>
    </div>
  </div>
</div>"""))
        elif 'pais' in cod:
            perder_vida()
            display(HTML(err_html('Casi. Revisa que sea exactamente: <code>pais = "Colombia"</code>')))
        else:
            perder_vida()
            display(HTML(err_html('Formato: <code>nombre_variable = "valor"</code>')))

def click_h10(b):
    with out10:
        clear_output(wait=True)
        G['xp'] = max(0, G['xp'] - 5)
        display(HTML(hint_html('Escribe exactamente: <code>pais = "Colombia"</code>')))

btn10_v.on_click(click_v10); btn10_h.on_click(click_h10)
display(area10)
display(widgets.HBox([btn10_v, btn10_h])); display(out10)