# -*- coding: utf-8 -*-
"""repeticion while.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1k-KXvO6qkNvLXb3DfPNZaRSIrBB_Mpgm

Crea un ejercicio que resuelva una ecuación cuadratica pidiendo los valores de a, b y c
"""

print("ecuacion cuadratica es de la forma ax**2+bx+c")
uno=int(input("Ingrese el valor de a: "))
dos=int(input("Ingrese el valor de b: "))
tres=int(input("Ingrese el valor de c: "))
print("el discriminante es", dos**2 - 4*uno*tres)
print("x1 =", (-dos + (dos**2 - 4*uno*tres)**0.5) / (2*uno))
print("x2 =", (-dos - (dos**2 - 4*uno*tres)**0.5) / (2*uno))

"""ESTRUCTURA WHILE MIENTRAS
No se sabe cuantas veces se debe repetir la acción.

Sintaxis en python

while (condición inicialCI:
  parte del código a repetir
  Modificador de condición inicial CI
CI la CI debe tener un valor de verdad VERDADERO TRUE para  ingresar al while


"""

import random
opciones = {1: "🪨", 2: "🗞️", 3: "✂️"}
yo = int(input("Elige entre 1.🪨, 2.🗞️, 3.✂️: "))
print("Elegiste: {opciones[yo]}")

m=random.randint(1,5)

if me==1:
  print("Empate")
      elif me==1 and l==2:
              print("e maquina eligio 🗞️")
                   elif me==2 and l==3:
                       print(" maquina eligio ✂️")
                          elif me==3 and l==1:
                             print(" máquina eligio 🪨")
                                else: print("Ganaste")

while yo < 1 or yo > 3:
    yo = int(input("Valor no válido. Elige entre 1.🪨, 2.🗞️, 3.✂️: "))

while True:
    entrada = input("Elige entre 1.🪨, 2.📜, 3.✂️: ")
    if entrada in ("1", "2", "3"):
        yo = int(entrada)
        break
    print("Valor no válido. Debe ser 1, 2 o 3.")

print(f"Seleccionaste: {yo}")

import random

opciones = {1:"🪨", 2:"📜", 3:"✂️"}

while True:
    yo = int(input("1.🪨 2.📜 3.✂️: "))
    m = random.randint(1, 3)
    print(f"Tú: {opciones[yo]} | Máquina: {opciones[m]}")

    if yo == m: print("Empate")
    elif (yo==1 and m==3) or (yo==2 and m==1) or (yo==3 and m==2): print("Ganaste!")
    else: print("Perdiste!")

    if input("¿Continuar? si/no: ")  ("si"): break

print("Gracias por jugar.")