# -*- coding: utf-8 -*-
"""tareajava3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CUtkEF7Q6J25Mfwixox_60LAA3zwW030
"""

import java.util.Scanner;

public class Main {

    static Scanner scanner = new Scanner(System.in);

    public static void main(String[] args) {
        int opcion = -1;
        while (opcion != 0) {
            System.out.println("\n==============================");
            System.out.println("        MENU PRINCIPAL        ");
            System.out.println("==============================");
            System.out.println(" 1. Tabla de multiplicar");
            System.out.println(" 2. Suma de naturales");
            System.out.println(" 3. Factorial");
            System.out.println(" 4. Serie de Fibonacci");
            System.out.println(" 5. Adivina el color");
            System.out.println(" 6. Numeros pares (1-100)");
            System.out.println(" 7. Suma de digitos");
            System.out.println(" 8. Es primo?");
            System.out.println(" 9. Triangulo de asteriscos");
            System.out.println("10. Potenciacion");
            System.out.println(" 0. Salir");
            System.out.println("==============================");
            System.out.print("Elige una opcion: ");

            opcion = leerEnteroPositivo(false);

            switch (opcion) {
                case 1:  tablaMultiplicar(); break;
                case 2:  sumaNaturales();    break;
                case 3:  factorial();        break;
                case 4:  fibonacci();        break;
                case 5:  adivinarColor();    break;
                case 6:  numerosPares();     break;
                case 7:  sumaDigitos();      break;
                case 8:  esPrimo();          break;
                case 9:  triangulo();        break;
                case 10: potenciacion();     break;
                case 0:  System.out.println("\nHasta luego!"); break;
                default: System.out.println("Opcion no valida. Intenta de nuevo.");
            }
        }
        scanner.close();
    }

    // Utilidad: leer entero con validacion
    static int leerEntero() {
        while (!scanner.hasNextInt()) {
            System.out.print("Ingresa un numero entero valido: ");
            scanner.next();
        }
        return scanner.nextInt();
    }

    // Si soloPositivo=true rechaza 0 y negativos
    static int leerEnteroPositivo(boolean soloPositivo) {
        int valor;
        while (true) {
            valor = leerEntero();
            if (!soloPositivo || valor > 0) return valor;
            System.out.print("El numero debe ser mayor que 0: ");
        }
    }

    // 1. Tabla de multiplicar
    static void tablaMultiplicar() {
        System.out.print("\n1. De que numero quieres la tabla? (1-100): ");
        int num = leerEnteroPositivo(true);
        if (num > 100) { System.out.println("Numero fuera del rango permitido (1-100)."); return; }
        System.out.println("\nTabla del " + num);
        for (int i = 1; i <= 10; i++) {
            System.out.printf("  %3d x %2d = %4d%n", num, i, num * i);
        }
    }

    // 2. Suma de naturales
    static void sumaNaturales() {
        System.out.print("\n2. Hasta que numero quieres sumar?: ");
        int limite = leerEnteroPositivo(true);
        long suma = 0;
        for (int i = 1; i <= limite; i++) suma += i;
        System.out.println("La suma de 1 a " + limite + " es: " + suma);
    }

    // 3. Factorial
    static void factorial() {
        System.out.print("\n3. Dime un numero para el factorial (0-20): ");
        int n = leerEntero();
        if (n < 0) {
            System.out.println("No existen factoriales de negativos.");
            return;
        }
        if (n > 20) {
            System.out.println("Numero demasiado grande (max 20 para evitar desbordamiento).");
            return;
        }
        long resultado = 1;
        for (int i = 1; i <= n; i++) resultado *= i;
        System.out.println(n + "! = " + resultado);
    }

    // 4. Fibonacci
    static void fibonacci() {
        System.out.print("\n4. Cuantos numeros de Fibonacci quieres? (1-50): ");
        int n = leerEnteroPositivo(true);
        if (n > 50) { System.out.println("Maximo 50 terminos."); return; }
        System.out.print("Serie: ");
        long a = 0, b = 1;
        for (int i = 0; i < n; i++) {
            System.out.print(a + (i < n - 1 ? ", " : ""));
            long aux = a + b;
            a = b;
            b = aux;
        }
        System.out.println();
    }

    // 5. Adivinar color
    static void adivinarColor() {
        String secreto = "azul";
        int maxIntentos = 10;
        System.out.println("\n5. Adivina el color (tienes " + maxIntentos + " intentos):");
        scanner.nextLine();
        boolean adivinado = false;
        for (int intento = 1; intento <= maxIntentos; intento++) {
            System.out.print("Intento " + intento + "/" + maxIntentos + ": ");
            String respuesta = scanner.nextLine().trim().toLowerCase();
            if (respuesta.isEmpty()) { System.out.println("Escribe algo."); intento--; continue; }
            if (respuesta.equals(secreto)) {
                System.out.println("Felicidades! Adivinaste en " + intento + " intento(s).");
                adivinado = true;
                break;
            } else {
                System.out.println("Ese no es... Te quedan " + (maxIntentos - intento) + " intento(s).");
            }
        }
        if (!adivinado) System.out.println("Se acabaron los intentos. El color era: " + secreto);
    }

    // 6. Numeros pares
    static void numerosPares() {
        System.out.println("\n6. Numeros pares del 2 al 100:");
        int count = 0;
        for (int i = 2; i <= 100; i += 2) {
            System.out.printf("%4d", i);
            if (++count % 10 == 0) System.out.println();
        }
        System.out.println();
    }

    // 7. Suma de digitos
    static void sumaDigitos() {
        System.out.print("\n7. Escribe un numero entero positivo: ");
        int num = leerEnteroPositivo(true);
        int suma = 0, original = num;
        while (num > 0) {
            suma += num % 10;
            num /= 10;
        }
        System.out.println("Suma de digitos de " + original + " = " + suma);
    }

    // 8. Numero primo
    static void esPrimo() {
        System.out.print("\n8. Que numero quieres revisar si es primo?: ");
        int n = leerEntero();
        if (n < 2) {
            System.out.println(n + " NO es primo (debe ser >= 2).");
            return;
        }
        boolean primo = true;
        for (int d = 2; d <= Math.sqrt(n); d++) {
            if (n % d == 0) { primo = false; break; }
        }
        System.out.println(n + (primo ? " SI es primo." : " NO es primo."));
    }

    // 9. Triangulo de asteriscos
    static void triangulo() {
        System.out.print("\n9. De cuantos pisos quieres el triangulo? (1-30): ");
        int pisos = leerEnteroPositivo(true);
        if (pisos > 30) { System.out.println("Maximo 30 pisos."); return; }
        System.out.println();
        for (int fila = 1; fila <= pisos; fila++) {
            for (int i = 0; i < fila; i++) System.out.print("*");
            System.out.println();
        }
    }

    // 10. Potenciacion
    static void potenciacion() {
        System.out.print("\n10. Dime la base: ");
        int base = leerEntero();
        System.out.print("    Dime el exponente (>= 0): ");
        int exp = leerEntero();
        if (exp < 0) { System.out.println("El exponente no puede ser negativo."); return; }
        long resultado = 1;
        for (int i = 0; i < exp; i++) resultado *= base;
        System.out.println(base + " ^ " + exp + " = " + resultado);
    }
}
}