# -*- coding: utf-8 -*-
"""tarea.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fP_Cq2xLtvELPTN4Ryk_3jEkrBAwNVoz
"""

# 1. ECUACIÓN CUADRÁTICA
print("=== 1. ecuacion cuadratica ")
a = float(input("Ingrese a: "))
b = float(input("Ingrese b: "))
c = float(input("Ingrese c: "))

if a == 0:
    print("No es una ecuación cuadratica.")
else:
    d = b**2 - 4*a*c
    if d > 0:
        x1 = (-b + d**0.5) / (2*a)
        x2 = (-b - d**0.5) / (2*a)
        print("Dos soluciones:", x1, "y", x2)
    elif d == 0:
        print("Una solución:", -b/(2*a))
    else:
        print("No tiene soluciones.")

# 2. PAR O IMPAR (TERNARIO)
print("\n=== 2. par O impar ")
num = int(input("Ingrese un núm: "))
resultado = "Par" if num % 2 == 0 else "Impar"
print("Resultado:", resultado)

# 3. AÑO BISIESTO
print("\n=== 3. bisiesto ")
anio = int(input("Ingrese un año: "))

if (anio % 4 == 0 and anio % 100 != 0) or (anio % 400 == 0):
    print("Es bisiesto.")
else:
    print("No es bisiesto.")

# 4. TERCERA EDAD
print("\n=== 4. tercera edad ")
nombre = input("Ingrese su nombre: ")
edad = int(input("Ingrese su edad: "))

if edad >= 70:
    print(nombre, "tiene priorida.")
else:
    print(nombre, "no pertenece a la tercera edad.")

# 5. MAYOR DE TRES NÚMEROS
print("\n=== 5. cual num es mayor ")
n1 = float(input("Número 1: "))
n2 = float(input("Número 2: "))
n3 = float(input("Número 3: "))

if n1 >= n2 and n1 >= n3:
    print("El mayor es:", n1)
elif n2 >= n1 and n2 >= n3:
    print("El mayor es:", n2)
else:
    print("El mayor es:", n3)

# 6. TIPO DE TRIÁNGULO
print("\n=== 6. tipo de triangul ")
l1 = float(input("Lado 1: "))
l2 = float(input("Lado 2: "))
l3 = float(input("Lado 3: "))

if l1 == l2 == l3:
    print("Equilátero")
elif l1 == l2 or l1 == l3 or l2 == l3:
    print("Isósceles")
else:
    print("Escaleno")

# 7. IMC
print("\n=== 7. imc ")
nombre_imc = input("Nombre: ")
peso = float(input("Peso (kg): "))
altura = float(input("Altura (m): "))

imc = peso / (altura ** 2)

if imc < 18.5:
    print(nombre_imc, "- Bajo peso")
elif imc < 25:
    print(nombre_imc, "- Normal")
elif imc < 30:
    print(nombre_imc, "- Sobrepeso")
else:
    print(nombre_imc, "- Obesidad")

# 8. CALCULADORA
print("\n=== 8. calculadra ")
x = float(input("Número 1: "))
y = float(input("Número 2: "))
op = input("Operador (+, -, *, /): ")

if op == "+":
    print("Resultado:", x + y)
elif op == "-":
    print("Resultado:", x - y)
elif op == "*":
    print("Resultado:", x * y)
elif op == "/":
    if y != 0:
        print("Resultado:", x / y)
    else:
        print("No se puede dividir por cero.")
else:
    print("Operador inválido.")

# 9. CALIFICACIÓN
print("\n=== 9. calificación")
nota = int(input("Ingrese la nota (0-100): "))

if nota >= 90:
    print("A")
elif nota >= 80:
    print("B")
elif nota >= 70:
    print("C")
elif nota >= 60:
    print("D")
else:
    print("F")

# 10. DÍA DE LA SEMANA
print("\n=== 10. dia de la semana ")
dia = int(input("Ingrese un número (1-7): "))

if dia == 1:
    print("Lunes")
elif dia == 2:
    print("Martes")
elif dia == 3:
    print("Miércoles")
elif dia == 4:
    print("Jueves")
elif dia == 5:
    print("Viernes")
elif dia == 6:
    print("Sábado")
elif dia == 7:
    print("Domingo")
else:
    print("Número inválido")

# 11. VALIDAR TRIÁNGULO
print("\n=== 11. validar triangulo ")
t1 = float(input("Lado 1: "))
t2 = float(input("Lado 2: "))
t3 = float(input("Lado 3: "))

if t1 + t2 > t3 and t1 + t3 > t2 and t2 + t3 > t1:
    print("Forman triángulo")
    if t1 == t2 == t3:
        print("Equilátero")
    elif t1 == t2 or t1 == t3 or t2 == t3:
        print("Isósceles")
    else:
        print("Escaleno")
else:
    print("No forman triángulo")